<a href="https://colab.research.google.com/github/Bryan-eng-lng/Machine-Learning-Projects-/blob/main/IncomeDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Dependencies

In [1]:
import pandas as pd
import numpy as np

Lets Load the Data and Analyse

In [2]:
df = pd.read_csv("/content/adult.csv.zip")

In [3]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [4]:
df.tail()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [5]:
df.shape

(32561, 15)

In [6]:
df['capital.gain'].unique()

array([    0, 99999, 41310, 34095, 27828, 25236, 25124, 22040, 20051,
       18481, 15831, 15024, 15020, 14344, 14084, 13550, 11678, 10605,
       10566, 10520,  9562,  9386,  8614,  7978,  7896,  7688,  7443,
        7430,  7298,  6849,  6767,  6723,  6514,  6497,  6418,  6360,
        6097,  5721,  5556,  5455,  5178,  5060,  5013,  4934,  4931,
        4865,  4787,  4687,  4650,  4508,  4416,  4386,  4101,  4064,
        3942,  3908,  3887,  3818,  3781,  3674,  3471,  3464,  3456,
        3432,  3418,  3411,  3325,  3273,  3137,  3103,  2993,  2977,
        2964,  2961,  2936,  2907,  2885,  2829,  2653,  2635,  2597,
        2580,  2538,  2463,  2414,  2407,  2387,  2354,  2346,  2329,
        2290,  2228,  2202,  2176,  2174,  2105,  2062,  2050,  2036,
        2009,  1848,  1831,  1797,  1639,  1506,  1471,  1455,  1424,
        1409,  1173,  1151,  1111,  1086,  1055,   991,   914,   594,
         401,   114])

In [7]:
df.duplicated().sum()

np.int64(24)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32537 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32537 non-null  int64
 1   workclass       32537 non-null  object
 2   fnlwgt          32537 non-null  int64
 3   education       32537 non-null  object
 4   education.num   32537 non-null  int64
 5   marital.status  32537 non-null  object
 6   occupation      32537 non-null  object
 7   relationship    32537 non-null  object
 8   race            32537 non-null  object
 9   sex             32537 non-null  object
 10  capital.gain    32537 non-null  int64
 11  capital.loss    32537 non-null  int64
 12  hours.per.week  32537 non-null  int64
 13  native.country  32537 non-null  object
 14  income          32537 non-null  object
dtypes: int64(6), object(9)
memory usage: 4.0+ MB

In [11]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education.num      int64
marital.status    object
occupation        object
relationship      object
race              object
sex               object
capital.gain       int64
capital.loss       int64
hours.per.week     int64
native.country    object
income            object
dtype: object

In [12]:
df.head(20)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,Private,216864,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K
6,38,Private,150601,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K
7,74,State-gov,88638,Doctorate,16,Never-married,Prof-specialty,Other-relative,White,Female,0,3683,20,United-States,>50K
8,68,Federal-gov,422013,HS-grad,9,Divorced,Prof-specialty,Not-in-family,White,Female,0,3683,40,United-States,<=50K
9,41,Private,70037,Some-college,10,Never-married,Craft-repair,Unmarried,White,Male,0,3004,60,?,>50K
10,45,Private,172274,Doctorate,16,Divorced,Prof-specialty,Unmarried,Black,Female,0,3004,35,United-States,>50K
11,38,Self-emp-not-inc,164526,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,0,2824,45,United-States,>50K
12,52,Private,129177,Bachelors,13,Widowed,Other-service,Not-in-family,White,Female,0,2824,20,United-States,>50K
13,32,Private,136204,Masters,14,Separated,Exec-managerial,Not-in-family,White,Male,0,2824,55,United-States,>50K
14,51,?,172175,Doctorate,16,Never-married,?,Not-in-family,White,Male,0,2824,40,United-States,>50K
15,46,Private,45363,Prof-school,15,Divorced,Prof-specialty,Not-in-family,White,Male,0,2824,40,United-States,>50K
16,45,Private,172822,11th,7,Divorced,Transport-moving,Not-in-family,White,Male,0,2824,76,United-States,>50K
17,57,Private,317847,Masters,14,Divorced,Exec-managerial,Not-in-family,White,Male,0,2824,50,United-States,>50K
18,22,Private,119592,Assoc-acdm,12,Never-married,Handlers-cleaners,Not-in-family,Black,Male,0,2824,40,?,>50K
19,34,Private,203034,Bachelors,13,Separated,Sales,Not-in-family,White,Male,0,2824,50,United-States,>50K

In [13]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [14]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [15]:
df.workclass.value_counts()

workclass
Private             22673
Self-emp-not-inc     2540
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [16]:
1836/3

612.0

In [17]:
612 + 612

1224

In [18]:
other_idx = df[df['workclass']== '?'].index

other_idx = other_idx.to_series().sample(frac=1 , random_state=42)


df.loc[other_idx[0:612],'workclass'] = 'Private'
df.loc[other_idx[612:1224],'workclass'] = 'Self-emp-not-inc'
df.loc[other_idx[1224:1836] , 'workclass'] = "Local-gov"

In [19]:
df.workclass.value_counts()

workclass
Private             23285
Self-emp-not-inc     3152
Local-gov            2705
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['workclass'] = le.fit_transform(df['workclass'])

In [21]:
df.workclass.value_counts()

workclass
3    23285
5     3152
1     2705
6     1298
4     1116
0      960
7       14
2        7
Name: count, dtype: int64

In [22]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [23]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,5,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,3,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,1,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,3,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,3,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [24]:
df.education.value_counts()

education
HS-grad         10494
Some-college     7282
Bachelors        5353
Masters          1722
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           645
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           332
1st-4th           166
Preschool          50
Name: count, dtype: int64

In [25]:
df['education.num'].value_counts()

education.num
9     10494
10     7282
13     5353
14     1722
11     1382
7      1175
12     1067
6       933
4       645
15      576
5       514
8       433
16      413
3       332
2       166
1        50
Name: count, dtype: int64

In [26]:
df.drop(columns=['education.num'],inplace=True)

In [27]:
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,5,77053,HS-grad,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,3,132870,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,1,186061,Some-college,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,3,140359,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,3,264663,Some-college,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [28]:
df['eduaction'] = le.fit_transform(df['education'])

In [29]:
df['eduaction'].value_counts()

eduaction
11    10494
15     7282
9      5353
12     1722
8      1382
1      1175
7      1067
0       933
5       645
14      576
6       514
2       433
10      413
4       332
3       166
13       50
Name: count, dtype: int64

In [30]:
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,77053,HS-grad,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,132870,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,186061,Some-college,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,140359,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,264663,Some-college,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [31]:
df['marital.status'].value_counts()

marital.status
Married-civ-spouse       14970
Never-married            10667
Divorced                  4441
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [32]:
df['marital.status'] = le.fit_transform(df['marital.status'])

In [33]:
df['marital.status'].value_counts()

marital.status
2    14970
4    10667
0     4441
5     1025
6      993
3      418
1       23
Name: count, dtype: int64

In [34]:
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,77053,HS-grad,6,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,132870,HS-grad,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,186061,Some-college,6,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,140359,7th-8th,0,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,264663,Some-college,5,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [35]:
df['education'] = le.fit_transform(df['eduaction'])

In [36]:
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,77053,11,6,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,132870,11,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,186061,15,6,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,140359,5,0,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,264663,15,5,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [37]:
df.education.value_counts()

education
11    10494
15     7282
9      5353
12     1722
8      1382
1      1175
7      1067
0       933
5       645
14      576
6       514
2       433
10      413
4       332
3       166
13       50
Name: count, dtype: int64

In [38]:
df.head()

,age,workclass,fnlwgt,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,77053,11,6,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,132870,11,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,186061,15,6,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,140359,5,0,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,264663,15,5,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [39]:
df = df.drop(columns=['fnlwgt'])

In [40]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,11,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,15,6,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,5,0,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,15,5,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [41]:
df['marital.status'].value_counts()

marital.status
2    14970
4    10667
0     4441
5     1025
6      993
3      418
1       23
Name: count, dtype: int64

In [42]:
df['marital.status'] = le.fit_transform(df['marital.status'])

In [43]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,11,6,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,15,6,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,5,0,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,15,5,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [44]:
df['occupation'].value_counts()

occupation
Prof-specialty       4136
Craft-repair         4094
Exec-managerial      4065
Adm-clerical         3768
Sales                3650
Other-service        3291
Machine-op-inspct    2000
?                    1843
Transport-moving     1597
Handlers-cleaners    1369
Farming-fishing       992
Tech-support          927
Protective-serv       649
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64

In [45]:
mode_value = df['occupation'].mode()[0]

print(mode_value)

Prof-specialty

In [46]:
df['occupation'] = df['occupation'].replace(
    '?',
    mode_value
)

In [47]:
df['occupation'].value_counts()

occupation
Prof-specialty       5979
Craft-repair         4094
Exec-managerial      4065
Adm-clerical         3768
Sales                3650
Other-service        3291
Machine-op-inspct    2000
Transport-moving     1597
Handlers-cleaners    1369
Farming-fishing       992
Tech-support          927
Protective-serv       649
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64

In [48]:
df['occupation'] = le.fit_transform(df['occupation'])

In [49]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,Not-in-family,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,11,6,3,Not-in-family,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,15,6,9,Unmarried,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,5,0,6,Unmarried,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,15,5,9,Own-child,White,Female,0,3900,40,United-States,<=50K,15

In [50]:
df['relationship'].value_counts()

relationship
Husband           13187
Not-in-family      8292
Own-child          5064
Unmarried          3445
Wife               1568
Other-relative      981
Name: count, dtype: int64

In [51]:
df['relationship'] = le.fit_transform(df['relationship'])

In [52]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,1,White,Female,0,4356,40,United-States,<=50K,11
1,82,3,11,6,3,1,White,Female,0,4356,18,United-States,<=50K,11
2,66,1,15,6,9,4,Black,Female,0,4356,40,United-States,<=50K,15
3,54,3,5,0,6,4,White,Female,0,3900,40,United-States,<=50K,5
4,41,3,15,5,9,3,White,Female,0,3900,40,United-States,<=50K,15

In [53]:
df['race'].value_counts()

race
White                 27795
Black                  3122
Asian-Pac-Islander     1038
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [54]:
df = df.drop(columns=['race'])

In [55]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,1,Female,0,4356,40,United-States,<=50K,11
1,82,3,11,6,3,1,Female,0,4356,18,United-States,<=50K,11
2,66,1,15,6,9,4,Female,0,4356,40,United-States,<=50K,15
3,54,3,5,0,6,4,Female,0,3900,40,United-States,<=50K,5
4,41,3,15,5,9,3,Female,0,3900,40,United-States,<=50K,15

In [56]:
df['sex'].value_counts()

sex
Male      21775
Female    10762
Name: count, dtype: int64

In [57]:
df['sex'] = le.fit_transform(df['sex'])

In [58]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,1,0,0,4356,40,United-States,<=50K,11
1,82,3,11,6,3,1,0,0,4356,18,United-States,<=50K,11
2,66,1,15,6,9,4,0,0,4356,40,United-States,<=50K,15
3,54,3,5,0,6,4,0,0,3900,40,United-States,<=50K,5
4,41,3,15,5,9,3,0,0,3900,40,United-States,<=50K,15

In [59]:
df['capital.gain'].value_counts()

capital.gain
0        29825
15024      347
7688       284
7298       246
99999      159
         ...
2538         1
2387         1
1455         1
1639         1
1111         1
Name: count, Length: 119, dtype: int64

In [60]:
df['hours.per.week'].value_counts()

hours.per.week
40    15204
50     2817
45     1823
60     1475
35     1296
      ...
87        1
94        1
82        1
92        1
74        1
Name: count, Length: 94, dtype: int64

In [61]:
df['native.country'].value_counts()

native.country
United-States                 29153
Mexico                          639
?                               582
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        62
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                           29
Ecuador                          28
Ireland                          24
Hong                             20
Trinadad&Tobago                  19
Cambodia                         19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Hungary                          13
Honduras                         13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [62]:
mode_value = df['native.country'].mode()[0]

print(mode_value)

United-States

In [63]:
df['native.country'] = df['native.country'].replace(
    '?',
    mode_value
)

In [64]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,1,0,0,4356,40,United-States,<=50K,11
1,82,3,11,6,3,1,0,0,4356,18,United-States,<=50K,11
2,66,1,15,6,9,4,0,0,4356,40,United-States,<=50K,15
3,54,3,5,0,6,4,0,0,3900,40,United-States,<=50K,5
4,41,3,15,5,9,3,0,0,3900,40,United-States,<=50K,15

In [65]:
df['native.country'] = le.fit_transform(df['native.country'])

In [66]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,1,0,0,4356,40,38,<=50K,11
1,82,3,11,6,3,1,0,0,4356,18,38,<=50K,11
2,66,1,15,6,9,4,0,0,4356,40,38,<=50K,15
3,54,3,5,0,6,4,0,0,3900,40,38,<=50K,5
4,41,3,15,5,9,3,0,0,3900,40,38,<=50K,15

In [67]:
df['income'] = le.fit_transform(df['income'])

In [68]:
df.head()

,age,workclass,education,marital.status,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
0,90,5,11,6,9,1,0,0,4356,40,38,0,11
1,82,3,11,6,3,1,0,0,4356,18,38,0,11
2,66,1,15,6,9,4,0,0,4356,40,38,0,15
3,54,3,5,0,6,4,0,0,3900,40,38,0,5
4,41,3,15,5,9,3,0,0,3900,40,38,0,15

0 is <=50k and 1 is >50k

In [69]:
df.tail()

,age,workclass,education,marital.status,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,eduaction
32556,22,3,15,4,10,1,1,0,0,40,38,0,15
32557,27,3,7,2,12,5,0,0,0,38,38,0,7
32558,40,3,11,2,6,0,1,0,0,40,38,1,11
32559,58,3,11,6,0,4,0,0,0,40,38,0,11
32560,22,3,11,4,0,3,1,0,0,20,38,0,11

In [94]:
df.shape

(32537, 13)

Lets Split and Train the Data

In [70]:
X = df.drop(columns=['income'])


y = df['income']

In [71]:
from sklearn.model_selection import train_test_split

X_train , X_test  , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state = 42)

In [72]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

Lets Implement Artificial Neural Network

In [73]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout , BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import mean_squared_error , r2_score

In [74]:
model = Sequential()

model.add(Dense(256, activation='relu', input_shape=(X_train.shape[1],)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(64, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(32, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [75]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [77]:
model.fit(X_train_scaled  , y_train , epochs=100 , batch_size=32)

Epoch 1/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7952 - loss: 0.4025
Epoch 2/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8137 - loss: 0.3714
Epoch 3/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8180 - loss: 0.3618
Epoch 4/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8198 - loss: 0.3625
Epoch 5/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8225 - loss: 0.3607
Epoch 6/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8249 - loss: 0.3590
Epoch 7/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8252 - loss: 0.3538
Epoch 8/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8283 - loss: 0.3504
Epoch 9/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8292 - loss: 0.3482
Epoch 10/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8286 - loss: 0.3491
Epoch 11/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8282 - loss: 0.3504
Epoch 12/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8376 - loss: 0.3423
Epoch 13/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8253 - loss: 0.3500
Epoch 14/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8290 - loss: 0.3420
Epoch 15/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8294 - loss: 0.3455
Epoch 16/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8350 - loss: 0.3407
Epoch 17/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8346 - loss: 0.3419
Epoch 18/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8353 - loss: 0.3436
Epoch 19/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8425 - loss: 0.3321
Epoch 20/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8381 - loss: 0.3355
Epoch 21/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8426 - loss: 0.3303
Epoch 22/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8402 - loss: 0.3321
Epoch 23/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8391 - loss: 0.3348
Epoch 24/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8444 - loss: 0.3313
Epoch 25/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8423 - loss: 0.3328
Epoch 26/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8427 - loss: 0.3268
Epoch 27/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8459 - loss: 0.3276
Epoch 28/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8484 - loss: 0.3256
Epoch 29/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8437 - loss: 0.3267
Epoch 30/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8493 - loss: 0.3257
Epoch 31/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8449 - loss: 0.3260
Epoch 32/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8414 - loss: 0.3287
Epoch 33/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8460 - loss: 0.3263
Epoch 34/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8471 - loss: 0.3276
Epoch 35/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8460 - loss: 0.3235
Epoch 36/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8441 - loss: 0.3227
Epoch 37/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8473 - loss: 0.3234
Epoch 38/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8461 - loss: 0.3305
Epoch 39/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8489 - loss: 0.3145
Epoch 40/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8476 - loss: 0.3236
Epoch 41/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8477 - loss: 0.3170
Epoch 42/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8516 - loss: 0.3184
Epoch 43/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8492 - loss: 0.3182
Epoch 44/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8546 - loss: 0.3156
Epoch 45/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8490 - loss: 0.3177
Epoch 46/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8467 - loss: 0.3189
Epoch 47/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8506 - loss: 0.3153
Epoch 48/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8478 - loss: 0.3174
Epoch 49/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8536 - loss: 0.3122
Epoch 50/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8528 - loss: 0.3090
Epoch 51/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8471 - loss: 0.3177
Epoch 52/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8527 - loss: 0.3097
Epoch 53/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8461 - loss: 0.3157
Epoch 54/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8507 - loss: 0.3164
Epoch 55/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8549 - loss: 0.3135
Epoch 56/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8476 - loss: 0.3197
Epoch 57/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8500 - loss: 0.3122
Epoch 58/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8508 - loss: 0.3098
Epoch 59/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8510 - loss: 0.3154
Epoch 60/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8561 - loss: 0.3129
Epoch 61/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8479 - loss: 0.3198
Epoch 62/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8537 - loss: 0.3056
Epoch 63/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8491 - loss: 0.3174
Epoch 64/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8532 - loss: 0.3145
Epoch 65/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8522 - loss: 0.3134
Epoch 66/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8537 - loss: 0.3102
Epoch 67/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8538 - loss: 0.3125
Epoch 68/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8587 - loss: 0.3018
Epoch 69/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8582 - loss: 0.3033
Epoch 70/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8518 - loss: 0.3095
Epoch 71/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8528 - loss: 0.3132
Epoch 72/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8497 - loss: 0.3154
Epoch 73/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8507 - loss: 0.3155
Epoch 74/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8506 - loss: 0.3105
Epoch 75/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8536 - loss: 0.3102
Epoch 76/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8533 - loss: 0.3106
Epoch 77/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8539 - loss: 0.3103
Epoch 78/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8516 - loss: 0.3095
Epoch 79/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8513 - loss: 0.3119
Epoch 80/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8576 - loss: 0.3022
Epoch 81/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8527 - loss: 0.3076
Epoch 82/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8570 - loss: 0.3038
Epoch 83/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8543 - loss: 0.3058
Epoch 84/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8557 - loss: 0.3061
Epoch 85/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8604 - loss: 0.3037
Epoch 86/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8563 - loss: 0.3067
Epoch 87/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8542 - loss: 0.3076
Epoch 88/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8588 - loss: 0.3020
Epoch 89/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8575 - loss: 0.3049
Epoch 90/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8583 - loss: 0.3013
Epoch 91/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8565 - loss: 0.3058
Epoch 92/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8548 - loss: 0.3078
Epoch 93/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8571 - loss: 0.3000
Epoch 94/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8574 - loss: 0.3007
Epoch 95/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8592 - loss: 0.3019
Epoch 96/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8545 - loss: 0.3057
Epoch 97/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8564 - loss: 0.3060
Epoch 98/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8559 - loss: 0.3028
Epoch 99/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8582 - loss: 0.3012
Epoch 100/100
814/814 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8563 - loss: 0.3057

In [79]:
test_acc = model.evaluate(X_test_scaled , y_test)

204/204 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8597 - loss: 0.3075