<a href="https://colab.research.google.com/github/Bryan-eng-lng/Machine-Learning-Projects-/blob/main/Laptop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

Lets load the data and analyse the data

In [ ]:
df = pd.read_csv("/content/laptopData (1).csv")

In [ ]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.duplicated().sum()

np.int64(29)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(1274, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1274 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 129.4+ KB

In [ ]:
df.dtypes

Unnamed: 0          float64
Company              object
TypeName             object
Inches               object
ScreenResolution     object
Cpu                  object
Ram                  object
Memory               object
Gpu                  object
OpSys                object
Weight               object
Price               float64
dtype: object

In [ ]:
df.isnull().sum()

Unnamed: 0          1
Company             1
TypeName            1
Inches              1
ScreenResolution    1
Cpu                 1
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
df = df.drop(columns=['Unnamed: 0'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram',
       'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

In [ ]:
df.Company.value_counts()

Company
Lenovo       290
Dell         287
HP           266
Asus         156
Acer         103
MSI           53
Toshiba       47
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
LG             3
Google         3
Huawei         2
Fujitsu        2
Name: count, dtype: int64

In [ ]:
df['Company'] = df['Company'].fillna(df['Company'].mode()[0])

In [ ]:
df.isnull().sum()

Company             0
TypeName            1
Inches              1
ScreenResolution    1
Cpu                 1
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()

df['Company'] = le.fit_transform(df['Company'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.TypeName.value_counts()

TypeName
Notebook              710
Gaming                203
Ultrabook             191
2 in 1 Convertible    116
Workstation            29
Netbook                24
Name: count, dtype: int64

In [ ]:
df['TypeName'] = df['TypeName'].fillna(df['TypeName'].mode()[0])

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              1
ScreenResolution    1
Cpu                 1
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
df['TypeName'] = le.fit_transform(df['TypeName'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.Inches.value_counts()

Inches
15.6    640
14      192
17.3    162
13.3    161
12.5     38
11.6     31
12        6
13.9      6
13.5      5
12.3      5
15.4      4
15        4
10.1      3
35.6      3
13        2
24        2
18.4      1
27.3      1
25.6      1
33.5      1
?         1
17        1
31.6      1
14.1      1
11.3      1
Name: count, dtype: int64

In [ ]:
df['Inches'] = df['Inches'].fillna(df['Inches'].mode()[0])

In [ ]:
df['Inches'] = le.fit_transform(df['Inches'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,7,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,14,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,13,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,7,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.ScreenResolution.value_counts()

ScreenResolution
Full HD 1920x1080                                495
1366x768                                         274
IPS Panel Full HD 1920x1080                      226
IPS Panel Full HD / Touchscreen 1920x1080         52
Full HD / Touchscreen 1920x1080                   45
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  14
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160                9
IPS Panel 1366x768                                 7
4K Ultra HD 3840x2160                              7
Touchscreen 2560x1440                              6
IPS Panel Retina Display 2304x1440                 6
IPS Panel Retina Display 2560x1600                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
1440x900                                           4
IPS Panel 2560x1440                                4
Touchscreen 2400x1600                              3
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1920x1200                    3
IPS Panel Touchscreen 1366x768                     3
Quad HD+ 3200x1800                                 3
2560x1440                                          3
1920x1080                                          3
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 2160x1440                        2
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1366x768                         1
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Retina Display 2736x1824                 1
Touchscreen / Full HD 1920x1080                    1
IPS Panel Full HD 1920x1200                        1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [ ]:
df['ScreenResolution'] = df['ScreenResolution'].fillna(df['ScreenResolution'].mode()[0])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,7,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,14,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,13,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,7,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 1
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
df['ScreenResolution']  = le.fit_transform(df['ScreenResolution'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,23,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,7,1,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,14,8,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,13,25,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,7,23,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.Cpu.value_counts()

Cpu
Intel Core i5 7200U 2.5GHz       183
Intel Core i7 7700HQ 2.8GHz      142
Intel Core i7 7500U 2.7GHz       128
Intel Core i7 8550U 1.8GHz        72
Intel Core i5 8250U 1.6GHz        68
                                ...
Intel Core i5 7200U 2.70GHz        1
Intel Core M M7-6Y75 1.2GHz        1
Intel Core M 6Y54 1.1GHz           1
AMD E-Series 9000 2.2GHz           1
Samsung Cortex A72&A53 2.0GHz      1
Name: count, Length: 118, dtype: int64

In [ ]:
df.Cpu.unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', nan, 'Intel Core i5 7300HQ 2.5GHz',
       'AMD E-Series E2-9000e 1.5GHz', 'Intel Core i5 1.6GHz',
       'Intel Core i7 8650U 1.9GHz', 'Intel Atom x5-Z8300 1.44GHz',
       'AMD E-Series E2-6110 1.5GHz', 'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'AMD A10-Series 9620P 2.5GHz', 'AMD E-Series 7110 1.8GHz',
       'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz'],
      dtype=object)

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 1
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
df['Cpu'] = df['Cpu'].fillna(df['Cpu'].mode()[0])

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 1
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
df.Ram.value_counts()

Ram
8GB     601
4GB     367
16GB    194
6GB      40
12GB     25
2GB      22
32GB     17
64GB      3
24GB      3
1GB       1
Name: count, dtype: int64

In [ ]:
df['Ram'] = df["Ram"].fillna(df['Ram'].mode()[0])

In [ ]:
df['Ram'] = le.fit_transform(df['Ram'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,23,Intel Core i5 2.3GHz,9,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,7,1,Intel Core i5 1.8GHz,9,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,14,8,Intel Core i5 7200U 2.5GHz,9,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,13,25,Intel Core i7 2.7GHz,1,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,7,23,Intel Core i5 3.1GHz,9,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.Memory.value_counts()

Memory
256GB SSD                        401
1TB HDD                          217
500GB HDD                        130
512GB SSD                        116
128GB SSD +  1TB HDD              92
128GB SSD                         74
256GB SSD +  1TB HDD              71
32GB Flash Storage                37
2TB HDD                           16
64GB Flash Storage                14
512GB SSD +  1TB HDD              14
1TB SSD                           13
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
128GB Flash Storage                4
180GB SSD                          4
16GB SSD                           3
512GB SSD +  2TB HDD               3
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
1TB SSD +  1TB HDD                 2
512GB Flash Storage                2
512GB SSD +  512GB SSD             1
64GB SSD                           1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
512GB SSD +  256GB SSD             1
?                                  1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              1
Gpu                 1
OpSys               1
Weight              1
Price               1
dtype: int64

In [ ]:
df['Memory'] = df['Memory'].fillna(df['Memory'].mode()[0])

In [ ]:
mode_value = df['Memory'].mode()[0]

print(mode_value)

256GB SSD

In [ ]:
df['Memory'] = df["Memory"].replace(
    '?',
    mode_value
)

In [ ]:
df.Memory.value_counts()

Memory
256GB SSD                        403
1TB HDD                          217
500GB HDD                        130
512GB SSD                        116
128GB SSD +  1TB HDD              92
128GB SSD                         74
256GB SSD +  1TB HDD              71
32GB Flash Storage                37
2TB HDD                           16
64GB Flash Storage                14
512GB SSD +  1TB HDD              14
1TB SSD                           13
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
128GB Flash Storage                4
180GB SSD                          4
16GB SSD                           3
512GB SSD +  2TB HDD               3
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
64GB SSD                           1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
512GB SSD +  256GB SSD             1
32GB HDD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [ ]:
df['Memory'] = le.fit_transform(df['Memory'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,23,Intel Core i5 2.3GHz,9,4,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,7,1,Intel Core i5 1.8GHz,9,2,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,14,8,Intel Core i5 7200U 2.5GHz,9,16,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,13,25,Intel Core i7 2.7GHz,1,29,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,7,23,Intel Core i5 3.1GHz,9,16,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.Gpu.value_counts()

Gpu
Intel HD Graphics 620      271
Intel HD Graphics 520      181
Intel UHD Graphics 620      66
Nvidia GeForce GTX 1050     64
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,23,Intel Core i5 2.3GHz,9,4,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,4,7,1,Intel Core i5 1.8GHz,9,2,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,7,3,14,8,Intel Core i5 7200U 2.5GHz,9,16,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,1,4,13,25,Intel Core i7 2.7GHz,1,29,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,1,4,7,23,Intel Core i5 3.1GHz,9,16,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.OpSys.value_counts()

OpSys
Windows 10      1047
No OS             63
Linux             61
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            1
Name: count, dtype: int64

In [ ]:
df['OpSys'] = df["OpSys"].fillna(df["OpSys"].mode()[0])

In [ ]:
df['OpSys'] = le.fit_transform(df['OpSys'])

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,23,Intel Core i5 2.3GHz,9,4,Intel Iris Plus Graphics 640,8,1.37kg,71378.6832
1,1,4,7,1,Intel Core i5 1.8GHz,9,2,Intel HD Graphics 6000,8,1.34kg,47895.5232
2,7,3,14,8,Intel Core i5 7200U 2.5GHz,9,16,Intel HD Graphics 620,4,1.86kg,30636.0000
3,1,4,13,25,Intel Core i7 2.7GHz,1,29,AMD Radeon Pro 455,8,1.83kg,135195.3360
4,1,4,7,23,Intel Core i5 3.1GHz,9,16,Intel Iris Plus Graphics 650,8,1.37kg,96095.8080

In [ ]:
df.Weight.value_counts()

Weight
2.2kg      111
2.1kg       57
2.4kg       43
2.3kg       41
2.5kg       37
          ...
3.52kg       1
2.21kg       1
2.191kg      1
2.34kg       1
4.0kg        1
Name: count, Length: 189, dtype: int64

In [ ]:
df['Weight'] = df["Weight"].fillna(df["Weight"].mode()[0])

In [ ]:
df['Weight'] = df.Weight.str.replace('kg','')

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,1,4,7,23,Intel Core i5 2.3GHz,9,4,Intel Iris Plus Graphics 640,8,1.37,71378.6832
1,1,4,7,1,Intel Core i5 1.8GHz,9,2,Intel HD Graphics 6000,8,1.34,47895.5232
2,7,3,14,8,Intel Core i5 7200U 2.5GHz,9,16,Intel HD Graphics 620,4,1.86,30636.0000
3,1,4,13,25,Intel Core i7 2.7GHz,1,29,AMD Radeon Pro 455,8,1.83,135195.3360
4,1,4,7,23,Intel Core i5 3.1GHz,9,16,Intel Iris Plus Graphics 650,8,1.37,96095.8080

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 1
OpSys               0
Weight              0
Price               1
dtype: int64

In [ ]:
df['Price'] = df['Price'].fillna(df["Price"].mean())

In [ ]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 1
OpSys               0
Weight              0
Price               0
dtype: int64

In [ ]:
df["Gpu"]  = df['Gpu'].fillna(df['Gpu'].mode()[0])

In [ ]:
df['Cpu_brand'] = df['Cpu'].apply(lambda x: x.split()[0])

def cpu_series(cpu):
    if 'i3' in cpu:
        return 'i3'
    elif 'i5' in cpu:
        return 'i5'
    elif 'i7' in cpu:
        return 'i7'
    else:
        return 'Other'

df['Cpu_series'] = df['Cpu'].apply(cpu_series)

df['Cpu_speed'] = df['Cpu'].str.extract(r'(\d+\.\d+)').astype(float)

df.drop(columns=['Cpu'], inplace=True)


df['Gpu_brand'] = df['Gpu'].apply(lambda x: x.split()[0])

def gpu_type(gpu):
    if 'Intel' in gpu:
        return 'Integrated'
    else:
        return 'Dedicated'

df['Gpu_type'] = df['Gpu'].apply(gpu_type)

df.drop(columns=['Gpu'], inplace=True)


df = pd.get_dummies(
    df,
    columns=['Cpu_brand', 'Cpu_series', 'Gpu_brand', 'Gpu_type'],
    drop_first=True
)

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Ram,Memory,OpSys,Weight,Price,Cpu_speed,Cpu_brand_Intel,Cpu_brand_Samsung,Cpu_series_i3,Cpu_series_i5,Cpu_series_i7,Gpu_brand_ARM,Gpu_brand_Intel,Gpu_brand_Nvidia,Gpu_type_Integrated
0,1,4,7,23,9,4,8,1.37,71378.6832,2.3,True,False,False,True,False,False,True,False,True
1,1,4,7,1,9,2,8,1.34,47895.5232,1.8,True,False,False,True,False,False,True,False,True
2,7,3,14,8,9,16,4,1.86,30636.0000,2.5,True,False,False,True,False,False,True,False,True
3,1,4,13,25,1,29,8,1.83,135195.3360,2.7,True,False,False,False,True,False,False,False,False
4,1,4,7,23,9,16,8,1.37,96095.8080,3.1,True,False,False,True,False,False,True,False,True

In [ ]:
# Encoding

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1274 entries, 0 to 1302
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company              1274 non-null   int64
 1   TypeName             1274 non-null   int64
 2   Inches               1274 non-null   int64
 3   ScreenResolution     1274 non-null   int64
 4   Ram                  1274 non-null   int64
 5   Memory               1274 non-null   int64
 6   OpSys                1274 non-null   int64
 7   Weight               1274 non-null   object
 8   Price                1274 non-null   float64
 9   Cpu_speed            1190 non-null   float64
 10  Cpu_brand_Intel      1274 non-null   bool
 11  Cpu_brand_Samsung    1274 non-null   bool
 12  Cpu_series_i3        1274 non-null   bool
 13  Cpu_series_i5        1274 non-null   bool
 14  Cpu_series_i7        1274 non-null   bool
 15  Gpu_brand_ARM        1274 non-null   bool
 16  Gpu_brand_Intel      1274 non-null   bool
 17  Gpu_brand_Nvidia     1274 non-null   bool
 18  Gpu_type_Integrated  1274 non-null   bool
dtypes: bool(9), float64(2), int64(7), object(1)
memory usage: 120.7+ KB

In [ ]:
for i in df.columns:
  if df.columns.dtype==bool:
    le.fit_transform(df[i])
  else:
    pass

In [ ]:
df.shape

(1274, 19)

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Ram,Memory,OpSys,Weight,Price,Cpu_speed,Cpu_brand_Intel,Cpu_brand_Samsung,Cpu_series_i3,Cpu_series_i5,Cpu_series_i7,Gpu_brand_ARM,Gpu_brand_Intel,Gpu_brand_Nvidia,Gpu_type_Integrated
0,1,4,7,23,9,4,8,1.37,71378.6832,2.3,True,False,False,True,False,False,True,False,True
1,1,4,7,1,9,2,8,1.34,47895.5232,1.8,True,False,False,True,False,False,True,False,True
2,7,3,14,8,9,16,4,1.86,30636.0000,2.5,True,False,False,True,False,False,True,False,True
3,1,4,13,25,1,29,8,1.83,135195.3360,2.7,True,False,False,False,True,False,False,False,False
4,1,4,7,23,9,16,8,1.37,96095.8080,3.1,True,False,False,True,False,False,True,False,True

In [ ]:
bool_cols = df.select_dtypes(include='bool').columns
for col in bool_cols:
    df[col] = df[col].astype(int)

df['Weight'] = pd.to_numeric(df['Weight'], errors='coerce')
df['Weight'] = df['Weight'].fillna(df['Weight'].mean()) # Ensure any NaNs from coerce are filled
df['Cpu_speed'] = df['Cpu_speed'].fillna(df['Cpu_speed'].mean())

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Ram,Memory,OpSys,Weight,Price,Cpu_speed,Cpu_brand_Intel,Cpu_brand_Samsung,Cpu_series_i3,Cpu_series_i5,Cpu_series_i7,Gpu_brand_ARM,Gpu_brand_Intel,Gpu_brand_Nvidia,Gpu_type_Integrated
0,1,4,7,23,9,4,8,1.37,71378.6832,2.3,1,0,0,1,0,0,1,0,1
1,1,4,7,1,9,2,8,1.34,47895.5232,1.8,1,0,0,1,0,0,1,0,1
2,7,3,14,8,9,16,4,1.86,30636.0000,2.5,1,0,0,1,0,0,1,0,1
3,1,4,13,25,1,29,8,1.83,135195.3360,2.7,1,0,0,0,1,0,0,0,0
4,1,4,7,23,9,16,8,1.37,96095.8080,3.1,1,0,0,1,0,0,1,0,1

Lets Split the Data and Train the Model

In [ ]:
X = df.drop(columns=['Price'])

y = df['Price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[ 0.84234957,  0.32434852,  0.53681116, ...,  0.8946247 ,
        -0.66430511,  0.8946247 ],
       [-1.08005628,  0.32434852,  0.53681116, ..., -1.11778715,
         1.5053324 , -1.11778715],
       [-1.56065774, -1.28007451,  0.53681116, ..., -1.11778715,
         1.5053324 , -1.11778715],
       ...,
       [ 0.84234957,  1.12656004, -0.54960507, ...,  0.8946247 ,
        -0.66430511,  0.8946247 ],
       [ 0.12144738, -2.08228602,  0.53681116, ...,  0.8946247 ,
        -0.66430511,  0.8946247 ],
       [-0.59945482, -1.28007451,  0.53681116, ..., -1.11778715,
         1.5053324 , -1.11778715]])

Lets Go With First LinearRegression

In [ ]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()

model.fit(X_train_scaled , y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import r2_score

score = r2_score(y_test , y_pred)

In [ ]:
score

0.4743418406544644

Lets Go With Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(
    criterion='squared_error',
    splitter='random',
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features=5,
    random_state=42,

)

In [ ]:
model.fit(X_train_scaled , y_train)

DecisionTreeRegressor(max_depth=5, max_features=5, random_state=42,
                      splitter='random')

In [ ]:
y_pred2 = model.predict(X_test_scaled)

In [ ]:
score2 = r2_score(y_test , y_pred2)

In [ ]:
score2

0.5704341363483226

In [ ]:
y_train = r2_score(y_train , model.predict(X_train_scaled))

In [ ]:
y_train

0.6200185785625598

Implementing Xgboost Model

In [ ]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

In [ ]:
X = df.drop(columns=['Price'])
y = df['Price']
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = XGBRegressor()


model.fit(X_train_scaled , y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_pred3 = model.predict(X_test_scaled)

In [ ]:
score3 = r2_score(y_test , y_pred3)

In [ ]:
score3

0.7750933811978875

In [ ]:
model = GridSearchCV(
    estimator=XGBRegressor(),
    param_grid={
        'learning_rate': [0.01, 0.1, 0.2],
        'max_depth': [3, 4, 5],
    },
    scoring='neg_mean_squared_error',
    cv=5,
    verbose=1
)

model.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bin=None,
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 4, 5]},
             scoring='neg_mean_squared_error', verbose=1)

In [ ]:
y_pred4 = model.predict(X_test_scaled)

score4 = r2_score(y_test , y_pred4)

In [ ]:
score4

0.8118126378519245

In [ ]:
y_train = r2_score(y_train , model.predict(X_train_scaled))

In [ ]:
y_train

0.9177338772093131