<a href="https://colab.research.google.com/github/Bryan-eng-lng/Machine-Learning-Projects-/blob/main/PhonePricePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lets Load the Data and Analyse the data

In [230]:
import pandas as pd

In [231]:
df = pd.read_csv("/content/mobiles.csv")

In [232]:
df.head(10)

,name,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung galaxy s24 fe 5g,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung galaxy s24 ultra,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung galaxy s25 edge,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung galaxy m36 5g,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung galaxy m06 5g,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung galaxy m35 5g,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung galaxy s25 fe,samsung,android,NaN,exynos 2400,10.0,NaN,1,1,0,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung galaxy a55 5g,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung galaxy a35 5g,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung galaxy f55 5g (8gb ram + 256gb),samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0

In [233]:
df.columns

Index(['name', 'brand', 'os', 'cpu_brand', 'cpu_name', 'cpu_cores',
       'cpu_speed', '5g', 'nfc', 'ir_blaster', 'ram', 'storage', 'battery',
       'screen_size', 'aspect_ratio_category', 'screen_res', 'refresh_rate',
       'ppi', 'rear_cameras', 'rear_primary', 'front_cameras', 'front_primary',
       'expandable_upto', 'spec_score', 'user_rating', 'price'],
      dtype='object')

In [234]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7166 entries, 0 to 7165
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   7166 non-null   object
 1   brand                  7166 non-null   object
 2   os                     7166 non-null   object
 3   cpu_brand              6151 non-null   object
 4   cpu_name               6366 non-null   object
 5   cpu_cores              7109 non-null   float64
 6   cpu_speed              6801 non-null   float64
 7   5g                     7166 non-null   int64
 8   nfc                    7166 non-null   int64
 9   ir_blaster             7166 non-null   int64
 10  ram                    7126 non-null   float64
 11  storage                7156 non-null   float64
 12  battery                7125 non-null   float64
 13  screen_size            7162 non-null   float64
 14  aspect_ratio_category  7144 non-null   object
 15  screen_res             7145 non-null   object
 16  refresh_rate           7166 non-null   int64
 17  ppi                    7141 non-null   float64
 18  rear_cameras           7166 non-null   int64
 19  rear_primary           7165 non-null   float64
 20  front_cameras          7166 non-null   int64
 21  front_primary          7117 non-null   float64
 22  expandable_upto        7166 non-null   float64
 23  spec_score             7166 non-null   int64
 24  user_rating            7166 non-null   float64
 25  price                  7166 non-null   float64
dtypes: float64(12), int64(7), object(7)
memory usage: 1.4+ MB

In [235]:
df.shape

(7166, 26)

In [236]:
df.duplicated().sum()

np.int64(0)

In [237]:
df.isnull().sum()

name                        0
brand                       0
os                          0
cpu_brand                1015
cpu_name                  800
cpu_cores                  57
cpu_speed                 365
5g                          0
nfc                         0
ir_blaster                  0
ram                        40
storage                    10
battery                    41
screen_size                 4
aspect_ratio_category      22
screen_res                 21
refresh_rate                0
ppi                        25
rear_cameras                0
rear_primary                1
front_cameras               0
front_primary              49
expandable_upto             0
spec_score                  0
user_rating                 0
price                       0
dtype: int64

In [238]:
df.drop(columns=['name'], inplace=True)

In [239]:
df.head()

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0

Lets Start Preprocessing Data

In [240]:
df.cpu_name.value_counts()

cpu_name
dimensity 6300        125
snapdragon 8 gen2      82
dimensity 700 5g       81
helio p22              81
helio p35              79
                     ...
spreadtrum 9832a        1
6737v                   1
mt6737v                 1
helio mt6591            1
spreadtrum sc7731g      1
Name: count, Length: 833, dtype: int64

In [241]:
df.cpu_speed.value_counts()

cpu_speed
2.000    1002
2.200     864
2.400     593
1.300     505
2.300     389
         ...
3.190       1
2.190       1
1.990       1
0.002       1
1.830       1
Name: count, Length: 80, dtype: int64

In [242]:
df.cpu_cores.value_counts()

cpu_cores
8.0     5739
4.0     1182
6.0      120
2.0       35
10.0      17
1.0        7
9.0        7
7.0        2
Name: count, dtype: int64

In [243]:
df.head(20)

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,6.0,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,NaN,exynos 2400,10.0,NaN,1,1,0,8.0,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0
10,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,498.01,1,200.0,1,12.0,0.0,93,4.15,129999.0
11,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.25,50399.0
12,samsung,android,snapdragon,snapdragon 6 gen3,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,81,4.70,30999.0
13,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,383.51,3,50.0,1,50.0,1024.0,79,4.50,45990.0
14,samsung,android,NaN,NaN,8.0,NaN,1,0,0,12.0,...,144,562.68,1,50.0,1,50.0,0.0,83,4.45,159990.0
15,samsung,android,exynos,exynos 1580,8.0,2.90,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,83,4.30,38999.0
16,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,415.68,3,50.0,1,12.0,0.0,87,4.35,80999.0
17,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,6.0,...,90,260.32,2,50.0,1,8.0,1536.0,74,4.30,9799.0
18,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.65,13499.0
19,samsung,android,NaN,NaN,8.0,NaN,1,1,0,6.0,...,120,382.38,3,50.0,1,32.0,1024.0,74,4.10,24990.0

In [244]:
df.head(50)

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,6.0,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,NaN,exynos 2400,10.0,NaN,1,1,0,8.0,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0
10,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,498.01,1,200.0,1,12.0,0.0,93,4.15,129999.0
11,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.25,50399.0
12,samsung,android,snapdragon,snapdragon 6 gen3,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,81,4.70,30999.0
13,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,383.51,3,50.0,1,50.0,1024.0,79,4.50,45990.0
14,samsung,android,NaN,NaN,8.0,NaN,1,0,0,12.0,...,144,562.68,1,50.0,1,50.0,0.0,83,4.45,159990.0
15,samsung,android,exynos,exynos 1580,8.0,2.90,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,83,4.30,38999.0
16,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,415.68,3,50.0,1,12.0,0.0,87,4.35,80999.0
17,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,6.0,...,90,260.32,2,50.0,1,8.0,1536.0,74,4.30,9799.0
18,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.65,13499.0
19,samsung,android,NaN,NaN,8.0,NaN,1,1,0,6.0,...,120,382.38,3,50.0,1,32.0,1024.0,74,4.10,24990.0
20,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.35,27999.0
21,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,85,4.35,41480.0
22,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.50,27998.0
23,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,12.0,...,120,512.88,3,50.0,1,12.0,0.0,87,4.15,57000.0
24,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.55,16999.0
25,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.60,16372.0
26,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,13.0,2048.0,82,4.15,20590.0
27,samsung,android,helio,helio g85,8.0,2.00,0,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,69,4.45,6249.0
28,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,74,4.45,10749.0
29,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,261.87,2,50.0,1,8.0,1024.0,74,4.00,9695.0
30,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.10,109999.0
31,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,81,4.75,15429.0
32,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.60,27999.0
33,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,75,4.20,10749.0
34,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.65,44170.0
35,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,12.0,...,120,501.07,1,200.0,1,12.0,0.0,91,4.05,89499.0
36,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,6.0,...,90,384.66,3,50.0,1,13.0,1536.0,78,4.10,11999.0
37,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,406.96,3,200.0,2,10.0,0.0,94,4.40,169990.0
38,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.05,17799.0
39,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,8.0,...,120,422.49,3,50.0,1,12.0,0.0,85,4.20,44999.0
40,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,83,4.25,23043.0
41,samsung,android,mediatek,dimensity 6100 plus,8.0,2.20,1,0,0,6.0,...,90,399.57,3,50.0,1,13.0,1024.0,75,4.15,12165.0
42,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,93,4.30,86999.0
43,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,582.78,3,200.0,1,12.0,0.0,80,4.00,49990.0
44,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,70,4.65,7999.0
45,samsung,android,snapdragon,snapdragon 7+ gen2,8.0,2.91,1,1,0,8.0,...,120,389.79,1,108.0,1,32.0,1024.0,89,4.75,42990.0
46,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,12.0,...,120,392.81,3,50.0,1,50.0,1024.0,85,4.50,23999.0
47,samsung,android,exynos,exynos 2200,8.0,2.80,1,1,0,8.0,...,120,402.69,3,50.0,1,10.0,0.0,81,4.55,37850.0
48,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,12.0,...,120,390.49,3,50.0,1,32.0,1024.0,86,4.15,30999.0
49,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,70,4.05,7999.0

In [245]:
df.head(60)

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,6.0,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,NaN,exynos 2400,10.0,NaN,1,1,0,8.0,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0
10,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,498.01,1,200.0,1,12.0,0.0,93,4.15,129999.0
11,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.25,50399.0
12,samsung,android,snapdragon,snapdragon 6 gen3,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,81,4.70,30999.0
13,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,383.51,3,50.0,1,50.0,1024.0,79,4.50,45990.0
14,samsung,android,NaN,NaN,8.0,NaN,1,0,0,12.0,...,144,562.68,1,50.0,1,50.0,0.0,83,4.45,159990.0
15,samsung,android,exynos,exynos 1580,8.0,2.90,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,83,4.30,38999.0
16,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,415.68,3,50.0,1,12.0,0.0,87,4.35,80999.0
17,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,6.0,...,90,260.32,2,50.0,1,8.0,1536.0,74,4.30,9799.0
18,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.65,13499.0
19,samsung,android,NaN,NaN,8.0,NaN,1,1,0,6.0,...,120,382.38,3,50.0,1,32.0,1024.0,74,4.10,24990.0
20,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.35,27999.0
21,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,85,4.35,41480.0
22,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.50,27998.0
23,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,12.0,...,120,512.88,3,50.0,1,12.0,0.0,87,4.15,57000.0
24,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.55,16999.0
25,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.60,16372.0
26,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,13.0,2048.0,82,4.15,20590.0
27,samsung,android,helio,helio g85,8.0,2.00,0,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,69,4.45,6249.0
28,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,74,4.45,10749.0
29,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,261.87,2,50.0,1,8.0,1024.0,74,4.00,9695.0
30,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.10,109999.0
31,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,81,4.75,15429.0
32,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.60,27999.0
33,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,75,4.20,10749.0
34,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.65,44170.0
35,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,12.0,...,120,501.07,1,200.0,1,12.0,0.0,91,4.05,89499.0
36,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,6.0,...,90,384.66,3,50.0,1,13.0,1536.0,78,4.10,11999.0
37,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,406.96,3,200.0,2,10.0,0.0,94,4.40,169990.0
38,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.05,17799.0
39,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,8.0,...,120,422.49,3,50.0,1,12.0,0.0,85,4.20,44999.0
40,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,83,4.25,23043.0
41,samsung,android,mediatek,dimensity 6100 plus,8.0,2.20,1,0,0,6.0,...,90,399.57,3,50.0,1,13.0,1024.0,75,4.15,12165.0
42,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,93,4.30,86999.0
43,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,582.78,3,200.0,1,12.0,0.0,80,4.00,49990.0
44,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,70,4.65,7999.0
45,samsung,android,snapdragon,snapdragon 7+ gen2,8.0,2.91,1,1,0,8.0,...,120,389.79,1,108.0,1,32.0,1024.0,89,4.75,42990.0
46,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,12.0,...,120,392.81,3,50.0,1,50.0,1024.0,85,4.50,23999.0
47,samsung,android,exynos,exynos 2200,8.0,2.80,1,1,0,8.0,...,120,402.69,3,50.0,1,10.0,0.0,81,4.55,37850.0
48,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,12.0,...,120,390.49,3,50.0,1,32.0,1024.0,86,4.15,30999.0
49,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,70,4.05,7999.0
50,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.50,19220.0
51,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,72,4.05,8499.0
52,samsung,android,snapdragon,snapdragon 6 gen4,8.0,2.30,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,0.0,82,4.25,34990.0
53,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,6.0,...,90,384.66,3,50.0,1,13.0,1536.0,77,4.25,11999.0
54,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,498.01,1,200.0,1,12.0,0.0,93,4.65,141999.0
55,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,12.0,...,120,394.57,3,50.0,1,50.0,1024.0,86,4.75,24199.0
56,samsung,android,snapdragon,snapdragon 8 gen 3,8.0,3.39,1,1,0,12.0,...,120,374.72,3,50.0,2,10.0,0.0,90,4.45,129000.0
57,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,6.0,...,90,384.66,3,50.0,1,13.0,1536.0,78,4.60,15499.0
58,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,80,4.45,30999.0
59,samsung,android,exynos,exynos 1580,8.0,2.90,1,1,0,12.0,...,120,384.66,3,50.0,1,12.0,0.0,84,4.70,44999.0

\observing data from the above I observed
 exynos 2400e or 2400 have 10 cpu_core speed

In [246]:
df.cpu_cores.value_counts()

cpu_cores
8.0     5739
4.0     1182
6.0      120
2.0       35
10.0      17
1.0        7
9.0        7
7.0        2
Name: count, dtype: int64

In [247]:
df.cpu_name.value_counts()

cpu_name
dimensity 6300        125
snapdragon 8 gen2      82
dimensity 700 5g       81
helio p22              81
helio p35              79
                     ...
spreadtrum 9832a        1
6737v                   1
mt6737v                 1
helio mt6591            1
spreadtrum sc7731g      1
Name: count, Length: 833, dtype: int64

In [248]:
df.loc[df['cpu_name'].isna(), ['cpu_name' , 'cpu_cores']]

     cpu_name  cpu_cores
14        NaN        8.0
19        NaN        8.0
63        NaN        8.0
87        NaN        8.0
99        NaN        8.0
...       ...        ...
7084      NaN        8.0
7135      NaN        4.0
7145      NaN        8.0
7151      NaN        8.0
7160      NaN        4.0

[800 rows x 2 columns]

In [249]:
df.tail(50)

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
7116,meizu,android,other,spreadtrum sc9832e,4.0,1.3,0,0,0,2.0,...,60,295.41,1,13.0,1,8.0,128.0,48,4.75,3799.0
7117,meizu,android,other,sc9832e,4.0,1.3,0,0,0,3.0,...,60,295.41,1,13.0,1,13.0,128.0,53,4.15,4850.0
7118,meizu,android,mediatek,mt6739,8.0,1.5,0,0,0,3.0,...,60,282.45,1,13.0,1,5.0,128.0,52,4.30,8999.0
7119,meizu,android,snapdragon,snapdragon 710,8.0,2.2,0,0,0,4.0,...,60,406.91,2,12.0,1,20.0,0.0,63,4.55,18990.0
7120,meizu,android,snapdragon,snapdragon 845,8.0,2.8,0,0,0,6.0,...,60,402.49,2,20.0,1,20.0,0.0,70,4.50,39230.0
7121,meizu,android,snapdragon,snapdragon 845,8.0,2.8,0,0,0,8.0,...,60,371.53,2,20.0,1,20.0,0.0,74,4.65,51783.0
7122,meizu,android,snapdragon,snapdragon 710,8.0,2.2,0,0,0,4.0,...,60,406.91,2,12.0,1,20.0,0.0,64,4.65,21990.0
7123,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,3.0,...,60,282.45,2,13.0,1,8.0,128.0,57,4.60,8999.0
7124,meizu,android,snapdragon,snapdragon 425,4.0,1.4,0,0,0,2.0,...,60,295.41,1,13.0,1,8.0,128.0,53,4.20,9999.0
7125,meizu,android,exynos,exynos 7885,8.0,2.1,0,0,0,3.0,...,60,282.45,1,16.0,1,16.0,128.0,55,3.95,10676.0
7126,meizu,android,exynos,exynos 8895,8.0,2.5,0,0,0,6.0,...,60,493.65,2,20.0,1,20.0,0.0,70,4.65,24990.0
7127,meizu,android,snapdragon,snapdragon 660,8.0,2.2,0,0,0,4.0,...,60,403.46,2,20.0,1,20.0,0.0,68,3.75,32667.0
7128,meizu,android,exynos,exynos 7872,6.0,1.6,0,0,0,3.0,...,60,282.45,1,13.0,1,5.0,256.0,57,4.15,16819.0
7129,meizu,android,helio,helio p10,8.0,1.8,0,0,0,2.0,...,60,400.53,1,13.0,1,5.0,0.0,54,4.25,10299.0
7130,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,3.0,...,60,282.42,1,13.0,1,8.0,256.0,55,4.00,11769.0
7131,meizu,android,snapdragon,snapdragon 625,8.0,2.0,0,0,0,3.0,...,60,400.53,2,12.0,1,16.0,256.0,62,4.10,8531.0
7132,meizu,android,helio,helio x30,10.0,2.6,0,1,0,6.0,...,60,515.30,2,12.0,1,16.0,0.0,71,4.45,24864.0
7133,meizu,android,helio,helio mt6737,4.0,1.3,0,0,0,2.0,...,60,293.72,1,8.0,1,5.0,0.0,48,3.30,5696.0
7134,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,2.0,...,60,282.42,1,13.0,1,5.0,256.0,51,3.40,6490.0
7135,meizu,android,NaN,NaN,4.0,1.3,0,0,0,2.0,...,60,293.72,1,8.0,1,5.0,0.0,48,4.25,6499.0
7136,meizu,android,helio,helio p20,8.0,2.3,0,0,0,4.0,...,60,400.53,1,13.0,1,8.0,0.0,63,4.20,13999.0
7137,meizu,android,helio,helio mt6753,8.0,1.3,0,0,0,3.0,...,60,282.42,1,13.0,1,5.0,256.0,52,4.25,7239.0
7138,meizu,android,helio,helio mt6750,8.0,1.5,0,1,0,3.0,...,60,282.42,1,13.0,1,5.0,128.0,53,3.80,5150.0
7139,meizu,android,helio,helio p20,8.0,2.3,0,0,0,3.0,...,60,400.53,1,12.0,1,5.0,0.0,59,3.65,16999.0
7140,meizu,android,exynos,exynos 8890,8.0,2.0,0,1,0,4.0,...,60,515.30,1,12.0,1,5.0,0.0,61,4.15,13821.0
7141,meizu,android,helio,helio p25,8.0,2.4,0,0,0,4.0,...,60,423.64,2,12.0,1,16.0,0.0,66,4.35,10999.0
7142,meizu,android,helio,helio x25,10.0,2.5,0,1,0,4.0,...,60,423.64,1,12.0,1,5.0,0.0,66,3.65,44015.0
7143,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,3.0,...,60,293.72,1,13.0,1,5.0,0.0,54,3.95,9999.0
7144,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,3.0,...,60,282.42,1,13.0,1,5.0,256.0,54,4.40,4990.0
7145,meizu,android,NaN,NaN,8.0,1.5,0,0,0,2.0,...,60,NaN,1,13.0,1,5.0,128.0,47,4.35,9999.0
7146,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,2.0,...,60,400.53,1,13.0,1,5.0,128.0,51,3.85,10999.0
7147,meizu,android,helio,helio p10,8.0,1.0,0,0,0,3.0,...,60,367.15,1,13.0,1,5.0,128.0,54,4.60,16999.0
7148,meizu,android,helio,helio p10,8.0,1.8,0,0,0,3.0,...,60,400.53,1,13.0,1,5.0,0.0,57,3.95,8775.0
7149,meizu,android,helio,helio x20,8.0,2.3,0,0,0,4.0,...,60,400.53,1,12.0,1,5.0,0.0,59,3.85,19999.0
7150,meizu,android,helio,helio mt6750,8.0,1.5,0,0,0,2.0,...,60,293.72,1,13.0,1,5.0,128.0,49,4.50,8999.0
7151,meizu,android,NaN,NaN,8.0,2.2,0,0,0,3.0,...,60,400.53,1,16.0,1,5.0,0.0,54,3.60,16999.0
7152,meizu,android,helio,helio a72,8.0,2.5,0,1,0,4.0,...,60,423.64,1,21.0,1,5.0,128.0,62,4.05,25999.0
7153,meizu,android,helio,helio mt6750,8.0,1.0,0,0,0,2.0,...,60,293.72,1,13.0,1,5.0,128.0,48,4.05,6999.0
7154,meizu,android,helio,helio mt6755,8.0,1.8,0,0,0,3.0,...,60,400.53,1,13.0,1,5.0,128.0,58,4.20,5290.0
7155,meizu,android,exynos,exynos 7420,8.0,2.1,0,0,0,3.0,...,60,386.47,1,21.6,1,5.0,128.0,62,3.40,31999.0
7156,meizu,android,helio,helio x10,8.0,2.2,0,0,0,3.0,...,60,400.53,1,13.0,1,5.0,128.0,58,4.40,12999.0
7157,meizu,android,exynos,exynos a53,8.0,1.5,0,0,0,3.0,...,60,386.47,1,21.0,1,5.0,128.0,61,3.00,29999.0
7158,meizu,android,exynos,exynos a53,8.0,1.5,0,0,0,4.0,...,60,386.47,1,21.0,1,5.0,128.0,64,4.40,32999.0
7159,meizu,android,helio,helio mt6732,4.0,1.5,0,0,0,1.0,...,60,298.54,1,13.0,1,5.0,0.0,48,3.35,5999.0
7160,meizu,android,NaN,NaN,4.0,1.3,0,0,0,2.0,...,60,293.72,1,13.0,1,5.0,128.0,48,4.25,5999.0
7161,meizu,android,helio,helio mt6753,8.0,1.3,0,0,0,2.0,...,60,400.53,1,13.0,1,5.0,128.0,53,4.30,4999.0
7162,meizu,android,helio,helio mt6795,8.0,2.2,0,0,0,3.0,...,60,400.53,1,20.7,1,5.0,0.0,58,4.15,14990.0
7163,meizu,android,helio,helio mt6752,8.0,1.7,0,0,0,2.0,...,60,400.53,1,13.0,1,5.0,0.0,53,3.90,14499.0
7164,meizu,android,other,a17,8.0,2.2,0,0,0,2.0,...,60,417.74,1,20.7,1,2.0,0.0,60,4.35,23999.0
7165,meizu,android,exynos,exynos 5430,8.0,2.0,0,1,0,3.0,...,60,542.81,1,20.7,1,5.0,0.0,62,3.90,21990.0

4.0 = hellomt6732 ,  spreadtrum sc9832e, **sc9832e**

In [250]:
null_cpu_cores = df.loc[
    df['cpu_cores'].isna(),
    [ 'cpu_name', 'cpu_cores' , 'brand']
]

null_cpu_cores.head(50)

             cpu_name  cpu_cores     brand
211               NaN        NaN   samsung
513     exynos  7884b        NaN   samsung
633    snapdragon 823        NaN   samsung
634               NaN        NaN   samsung
2007  snapdragon  898        NaN  motorola
2391   dimensity 1100        NaN    xiaomi
2526   dimensity 1100        NaN    xiaomi
2680   snapdragon 820        NaN    xiaomi
3015    apple a19 pro        NaN     apple
3020    apple a19 pro        NaN     apple
3047       bionic a16        NaN     apple
3061       apple  a13        NaN     apple
3298              NaN        NaN     tecno
3393              NaN        NaN     honor
3536  dimensity  1100        NaN     honor
3548        krin 710a        NaN     honor
3646              NaN        NaN    huawei
3688   snapdragon 615        NaN     nokia
3690   snapdragon 775        NaN     nokia
3829   snapdragon 835        NaN     nokia
3842         tensor 5        NaN    google
3844        tensor g5        NaN    google
3849        tensor g5        NaN    google
3855  google tensor 6        NaN    google
3856        tensor g5        NaN    google
3858        tensor g4        NaN    google
3980            helio        NaN      lava
3984              NaN        NaN      lava
4059              NaN        NaN    huawei
4062              NaN        NaN    huawei
4064       kirin 9020        NaN    huawei
4075              NaN        NaN    huawei
4076              NaN        NaN    huawei
4079              NaN        NaN    huawei
4080              NaN        NaN    huawei
4173              NaN        NaN    huawei
4174      kirin  710a        NaN    huawei
4394     helio mt6735        NaN      sony
4755   snapdragon 410        NaN      asus
4757   snapdragon 615        NaN      asus
4803              NaN        NaN     ikall
4805              NaN        NaN     ikall
4806              NaN        NaN     ikall
4813              NaN        NaN     ikall
5669              NaN        NaN     spice
5691              NaN        NaN     spice
5698              NaN        NaN      jmax
5699              NaN        NaN      jmax
5702              NaN        NaN      jmax
5703              NaN        NaN      jmax

6.0 = exynos 7872 ,  // heliox30 , heliox25 = 10.0 , // 2.0 = heliomt6572

In [251]:
df = df[~df['cpu_cores'].isin([1.0, 9.0, 7.0])]

In [252]:
df.cpu_cores.value_counts()

cpu_cores
8.0     5739
4.0     1182
6.0      120
2.0       35
10.0      17
Name: count, dtype: int64

In [253]:
df.shape

(7150, 25)

In [254]:
core_to_cpu = {
    10.0: 'exynos 2400 / exynos 2400e',
    6.0: 'exynos 7872',
    4.0: 'helio mt6732 / spreadtrum sc9832e',
    2.0: 'helio mt6572'
}

In [255]:
df['cpu_name'] = df.apply(
    lambda x: core_to_cpu.get(x['cpu_cores'], x['cpu_name'])
    if pd.isna(x['cpu_name']) else x['cpu_name'],
    axis=1
)

In [256]:
df.loc[df['cpu_name'].isna(), ['cpu_cores', 'cpu_name']].head()

    cpu_cores cpu_name
14        8.0      NaN
19        8.0      NaN
63        8.0      NaN
87        8.0      NaN
99        8.0      NaN

In [257]:
df['cpu_name'].value_counts().head(10)

cpu_name
helio mt6732 / spreadtrum sc9832e    480
dimensity 6300                       125
snapdragon 8 gen2                     82
dimensity 700 5g                      81
helio p22                             81
helio p35                             79
snapdragon 845                        77
snapdragon 8 gen3                     75
snapdragon 8+ gen1                    75
helio g85                             66
Name: count, dtype: int64

In [258]:
df.isnull().sum()

brand                       0
os                          0
cpu_brand                1008
cpu_name                  294
cpu_cores                  57
cpu_speed                 362
5g                          0
nfc                         0
ir_blaster                  0
ram                        40
storage                    10
battery                    40
screen_size                 4
aspect_ratio_category      22
screen_res                 21
refresh_rate                0
ppi                        25
rear_cameras                0
rear_primary                1
front_cameras               0
front_primary              49
expandable_upto             0
spec_score                  0
user_rating                 0
price                       0
dtype: int64

In [259]:
df = df.dropna(subset=['cpu_name'])

In [260]:
df['cpu_name'].isna().sum()

np.int64(0)

In [261]:
rows_before = len(df)
df = df.dropna(subset=['cpu_name'])
rows_after = len(df)

rows_before - rows_after

0

In [262]:
df.reset_index(drop=True, inplace=True)

In [263]:
df.isnull().sum()

brand                      0
os                         0
cpu_brand                714
cpu_name                   0
cpu_cores                 28
cpu_speed                217
5g                         0
nfc                        0
ir_blaster                 0
ram                       29
storage                    5
battery                   32
screen_size                3
aspect_ratio_category     19
screen_res                18
refresh_rate               0
ppi                       21
rear_cameras               0
rear_primary               1
front_cameras              0
front_primary             45
expandable_upto            0
spec_score                 0
user_rating                0
price                      0
dtype: int64

In [264]:
df.loc[df['cpu_brand'].isna(), ['cpu_name' , 'cpu_brand']]

                               cpu_name cpu_brand
6                           exynos 2400       NaN
13                               exynos       NaN
41                               exynos       NaN
58                       dimensity 6400       NaN
79                               exynos       NaN
...                                 ...       ...
6764  helio mt6732 / spreadtrum sc9832e       NaN
6777                        unisoc t765       NaN
6778                snapdragon 7+ gen 3       NaN
6827  helio mt6732 / spreadtrum sc9832e       NaN
6850  helio mt6732 / spreadtrum sc9832e       NaN

[714 rows x 2 columns]

In [265]:
df.head(50)

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,6.0,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,NaN,exynos 2400,10.0,NaN,1,1,0,8.0,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0
10,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,498.01,1,200.0,1,12.0,0.0,93,4.15,129999.0
11,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.25,50399.0
12,samsung,android,snapdragon,snapdragon 6 gen3,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,81,4.70,30999.0
13,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,383.51,3,50.0,1,50.0,1024.0,79,4.50,45990.0
14,samsung,android,exynos,exynos 1580,8.0,2.90,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,83,4.30,38999.0
15,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,415.68,3,50.0,1,12.0,0.0,87,4.35,80999.0
16,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,6.0,...,90,260.32,2,50.0,1,8.0,1536.0,74,4.30,9799.0
17,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.65,13499.0
18,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.35,27999.0
19,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,85,4.35,41480.0
20,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.50,27998.0
21,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,12.0,...,120,512.88,3,50.0,1,12.0,0.0,87,4.15,57000.0
22,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.55,16999.0
23,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.60,16372.0
24,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,13.0,2048.0,82,4.15,20590.0
25,samsung,android,helio,helio g85,8.0,2.00,0,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,69,4.45,6249.0
26,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,74,4.45,10749.0
27,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,261.87,2,50.0,1,8.0,1024.0,74,4.00,9695.0
28,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.10,109999.0
29,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,81,4.75,15429.0
30,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.60,27999.0
31,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,75,4.20,10749.0
32,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.65,44170.0
33,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,12.0,...,120,501.07,1,200.0,1,12.0,0.0,91,4.05,89499.0
34,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,6.0,...,90,384.66,3,50.0,1,13.0,1536.0,78,4.10,11999.0
35,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,406.96,3,200.0,2,10.0,0.0,94,4.40,169990.0
36,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.05,17799.0
37,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,8.0,...,120,422.49,3,50.0,1,12.0,0.0,85,4.20,44999.0
38,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,83,4.25,23043.0
39,samsung,android,mediatek,dimensity 6100 plus,8.0,2.20,1,0,0,6.0,...,90,399.57,3,50.0,1,13.0,1024.0,75,4.15,12165.0
40,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,93,4.30,86999.0
41,samsung,android,NaN,exynos,8.0,NaN,1,1,0,8.0,...,120,582.78,3,200.0,1,12.0,0.0,80,4.00,49990.0
42,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,70,4.65,7999.0
43,samsung,android,snapdragon,snapdragon 7+ gen2,8.0,2.91,1,1,0,8.0,...,120,389.79,1,108.0,1,32.0,1024.0,89,4.75,42990.0
44,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,12.0,...,120,392.81,3,50.0,1,50.0,1024.0,85,4.50,23999.0
45,samsung,android,exynos,exynos 2200,8.0,2.80,1,1,0,8.0,...,120,402.69,3,50.0,1,10.0,0.0,81,4.55,37850.0
46,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,12.0,...,120,390.49,3,50.0,1,32.0,1024.0,86,4.15,30999.0
47,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,70,4.05,7999.0
48,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.50,19220.0
49,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,72,4.05,8499.0

In [266]:


def infer_cpu_brand(cpu_name):
    if pd.isna(cpu_name):
        return None

    name = cpu_name.lower()

    if 'snapdragon' in name:
        return 'snapdragon'
    elif 'exynos' in name:
        return 'exynos'
    elif 'dimensity' in name or 'helio' in name or 'mediatek' in name:
        return 'mediatek'
    elif 'unisoc' in name or 'spreadtrum' in name:
        return 'unisoc'
    else:
        return 'other'

In [267]:
df.loc[df['cpu_brand'].isna(), 'cpu_brand'] = (
    df.loc[df['cpu_brand'].isna(), 'cpu_name']
      .apply(infer_cpu_brand)
)

In [268]:
df.isnull().sum()

brand                      0
os                         0
cpu_brand                  0
cpu_name                   0
cpu_cores                 28
cpu_speed                217
5g                         0
nfc                        0
ir_blaster                 0
ram                       29
storage                    5
battery                   32
screen_size                3
aspect_ratio_category     19
screen_res                18
refresh_rate               0
ppi                       21
rear_cameras               0
rear_primary               1
front_cameras              0
front_primary             45
expandable_upto            0
spec_score                 0
user_rating                0
price                      0
dtype: int64

In [269]:
df.loc[df['cpu_cores'].isna(), ['cpu_name' , 'cpu_cores']]

             cpu_name  cpu_cores
482     exynos  7884b        NaN
597    snapdragon 823        NaN
1934  snapdragon  898        NaN
2309   dimensity 1100        NaN
2444   dimensity 1100        NaN
2595   snapdragon 820        NaN
2925    apple a19 pro        NaN
2930    apple a19 pro        NaN
2955       bionic a16        NaN
2969       apple  a13        NaN
3433  dimensity  1100        NaN
3445        krin 710a        NaN
3584   snapdragon 615        NaN
3586   snapdragon 775        NaN
3723   snapdragon 835        NaN
3733         tensor 5        NaN
3735        tensor g5        NaN
3739        tensor g5        NaN
3743  google tensor 6        NaN
3744        tensor g5        NaN
3746        tensor g4        NaN
3861            helio        NaN
3933       kirin 9020        NaN
4022      kirin  710a        NaN
4240     helio mt6735        NaN
4592   snapdragon 410        NaN
4594   snapdragon 615        NaN
6059   dimensity 1100        NaN

In [270]:
cpu_name_to_cores = {
    # Exynos
    'exynos 7884b': 8,

    # Snapdragon
    'snapdragon 410': 4,
    'snapdragon 615': 8,
    'snapdragon 820': 4,
    'snapdragon 823': 4,
    'snapdragon 835': 8,
    'snapdragon 775': 8,
    'snapdragon 898': 8,

    # MediaTek
    'dimensity 1100': 8,
    'helio mt6735': 4,

    # Apple
    'apple a13': 6,
    'bionic a16': 6,
    'apple a19 pro': 6,

    # Google Tensor
    'tensor 5': 8,
    'tensor g4': 8,
    'tensor g5': 8,
    'google tensor 6': 8,

    # Kirin
    'kirin 710a': 8,
    'kirin 9020': 8
}

In [271]:
df['cpu_cores'] = df.apply(
    lambda x: cpu_name_to_cores.get(x['cpu_name'], x['cpu_cores'])
    if pd.isna(x['cpu_cores']) else x['cpu_cores'],
    axis=1
)

In [272]:
df.isnull().sum()

brand                      0
os                         0
cpu_brand                  0
cpu_name                   0
cpu_cores                  7
cpu_speed                217
5g                         0
nfc                        0
ir_blaster                 0
ram                       29
storage                    5
battery                   32
screen_size                3
aspect_ratio_category     19
screen_res                18
refresh_rate               0
ppi                       21
rear_cameras               0
rear_primary               1
front_cameras              0
front_primary             45
expandable_upto            0
spec_score                 0
user_rating                0
price                      0
dtype: int64

In [273]:
df.dropna(subset=['cpu_cores'] , inplace=True)

In [274]:
df.isnull().sum()

brand                      0
os                         0
cpu_brand                  0
cpu_name                   0
cpu_cores                  0
cpu_speed                211
5g                         0
nfc                        0
ir_blaster                 0
ram                       29
storage                    5
battery                   32
screen_size                3
aspect_ratio_category     19
screen_res                18
refresh_rate               0
ppi                       21
rear_cameras               0
rear_primary               1
front_cameras              0
front_primary             45
expandable_upto            0
spec_score                 0
user_rating                0
price                      0
dtype: int64

In [275]:
df.cpu_speed.value_counts()

cpu_speed
2.00    984
2.20    857
2.40    592
1.30    486
2.30    383
       ...
2.19      1
1.65      1
1.99      1
1.83      1
1.14      1
Name: count, Length: 79, dtype: int64

In [276]:
df.loc[df['cpu_speed'].isna(), ['cpu_name' , 'cpu_cores' , 'cpu_speed']]

                               cpu_name  cpu_cores  cpu_speed
6                           exynos 2400       10.0        NaN
13                               exynos        8.0        NaN
41                               exynos        8.0        NaN
58                       dimensity 6400        8.0        NaN
79                               exynos        8.0        NaN
...                                 ...        ...        ...
6405  helio mt6732 / spreadtrum sc9832e        4.0        NaN
6616                     snapdragon 600        4.0        NaN
6707  helio mt6732 / spreadtrum sc9832e        4.0        NaN
6777                        unisoc t765        8.0        NaN
6778                snapdragon 7+ gen 3        8.0        NaN

[211 rows x 3 columns]

In [277]:
df.head(50)

,brand,os,cpu_brand,cpu_name,cpu_cores,cpu_speed,5g,nfc,ir_blaster,ram,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,6.0,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,exynos,exynos 2400,10.0,NaN,1,1,0,8.0,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0
10,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,498.01,1,200.0,1,12.0,0.0,93,4.15,129999.0
11,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.25,50399.0
12,samsung,android,snapdragon,snapdragon 6 gen3,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,81,4.70,30999.0
13,samsung,android,exynos,exynos,8.0,NaN,1,1,0,8.0,...,120,383.51,3,50.0,1,50.0,1024.0,79,4.50,45990.0
14,samsung,android,exynos,exynos 1580,8.0,2.90,1,1,0,8.0,...,120,384.66,3,50.0,1,12.0,0.0,83,4.30,38999.0
15,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,415.68,3,50.0,1,12.0,0.0,87,4.35,80999.0
16,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,6.0,...,90,260.32,2,50.0,1,8.0,1536.0,74,4.30,9799.0
17,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.65,13499.0
18,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.35,27999.0
19,samsung,android,exynos,exynos 2400e,10.0,3.11,1,1,0,8.0,...,120,384.66,3,50.0,1,10.0,0.0,85,4.35,41480.0
20,samsung,android,exynos,exynos 1480,8.0,2.70,1,0,0,8.0,...,120,382.38,3,50.0,1,12.0,0.0,79,4.50,27998.0
21,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,12.0,...,120,512.88,3,50.0,1,12.0,0.0,87,4.15,57000.0
22,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,8.0,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.55,16999.0
23,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.60,16372.0
24,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,384.66,3,50.0,1,13.0,2048.0,82,4.15,20590.0
25,samsung,android,helio,helio g85,8.0,2.00,0,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,69,4.45,6249.0
26,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,74,4.45,10749.0
27,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,261.87,2,50.0,1,8.0,1024.0,74,4.00,9695.0
28,samsung,android,snapdragon,snapdragon 8elite,8.0,4.47,1,1,0,12.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.10,109999.0
29,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,81,4.75,15429.0
30,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,8.0,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.60,27999.0
31,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,4.0,...,90,384.66,3,50.0,1,13.0,1536.0,75,4.20,10749.0
32,samsung,android,exynos,exynos 2400,10.0,3.20,1,1,0,8.0,...,120,415.68,3,50.0,1,12.0,0.0,86,4.65,44170.0
33,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,12.0,...,120,501.07,1,200.0,1,12.0,0.0,91,4.05,89499.0
34,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,1,0,6.0,...,90,384.66,3,50.0,1,13.0,1536.0,78,4.10,11999.0
35,samsung,android,snapdragon,snapdragon 8 elite,8.0,4.32,1,1,0,12.0,...,120,406.96,3,200.0,2,10.0,0.0,94,4.40,169990.0
36,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,8.0,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.05,17799.0
37,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,3.36,1,1,0,8.0,...,120,422.49,3,50.0,1,12.0,0.0,85,4.20,44999.0
38,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,83,4.25,23043.0
39,samsung,android,mediatek,dimensity 6100 plus,8.0,2.20,1,0,0,6.0,...,90,399.57,3,50.0,1,13.0,1024.0,75,4.15,12165.0
40,samsung,android,snapdragon,snapdragon 8 gen3,8.0,3.30,1,1,0,12.0,...,120,505.33,1,200.0,1,12.0,0.0,93,4.30,86999.0
41,samsung,android,exynos,exynos,8.0,NaN,1,1,0,8.0,...,120,582.78,3,200.0,1,12.0,0.0,80,4.00,49990.0
42,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,90,260.32,2,50.0,1,8.0,1536.0,70,4.65,7999.0
43,samsung,android,snapdragon,snapdragon 7+ gen2,8.0,2.91,1,1,0,8.0,...,120,389.79,1,108.0,1,32.0,1024.0,89,4.75,42990.0
44,samsung,android,snapdragon,snapdragon 7 gen1,8.0,2.40,1,1,0,12.0,...,120,392.81,3,50.0,1,50.0,1024.0,85,4.50,23999.0
45,samsung,android,exynos,exynos 2200,8.0,2.80,1,1,0,8.0,...,120,402.69,3,50.0,1,10.0,0.0,81,4.55,37850.0
46,samsung,android,exynos,exynos 1480,8.0,2.70,1,1,0,12.0,...,120,390.49,3,50.0,1,32.0,1024.0,86,4.15,30999.0
47,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,70,4.05,7999.0
48,samsung,android,exynos,exynos 1380,8.0,2.40,1,1,0,8.0,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.50,19220.0
49,samsung,android,mediatek,dimensity 6300,8.0,2.40,1,0,0,4.0,...,60,261.87,2,50.0,1,8.0,1024.0,72,4.05,8499.0

In [278]:
df.drop(columns=['cpu_speed'] , inplace=True)

In [279]:
df.head()

,brand,os,cpu_brand,cpu_name,cpu_cores,5g,nfc,ir_blaster,ram,storage,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,1,1,0,8.0,128.0,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,1,1,0,12.0,256.0,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,1,1,0,12.0,256.0,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,1,1,0,8.0,128.0,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,1,0,0,4.0,128.0,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0

In [280]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
nfc                       0
ir_blaster                0
ram                      29
storage                   5
battery                  32
screen_size               3
aspect_ratio_category    19
screen_res               18
refresh_rate              0
ppi                      21
rear_cameras              0
rear_primary              1
front_cameras             0
front_primary            45
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [281]:
df.drop(columns=['nfc' , 'ir_blaster'] , inplace=True)

In [282]:
df.head()

,brand,os,cpu_brand,cpu_name,cpu_cores,5g,ram,storage,battery,screen_size,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,1,8.0,128.0,4700.0,6.70,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,1,12.0,256.0,5000.0,6.80,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,1,12.0,256.0,3900.0,6.70,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,6500.0,6.74,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.74,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0

In [283]:
df.columns

Index(['brand', 'os', 'cpu_brand', 'cpu_name', 'cpu_cores', '5g', 'ram',
       'storage', 'battery', 'screen_size', 'aspect_ratio_category',
       'screen_res', 'refresh_rate', 'ppi', 'rear_cameras', 'rear_primary',
       'front_cameras', 'front_primary', 'expandable_upto', 'spec_score',
       'user_rating', 'price'],
      dtype='object')

In [284]:
df.ram.value_counts()

ram
8.0     1714
4.0     1431
6.0     1113
2.0      745
3.0      694
12.0     614
1.0      367
16.0      91
1.5       28
24.0      10
18.0       7
10.0       6
Name: count, dtype: int64

In [285]:
df.loc[df['ram'].isna() , ['ram' , 'storage']]

      ram  storage
2925  NaN    256.0
2929  NaN    128.0
2930  NaN    128.0
2940  NaN    256.0
2953  NaN     64.0
2959  NaN    512.0
2966  NaN     64.0
3932  NaN    256.0
3935  NaN    128.0
3941  NaN    128.0
3946  NaN    512.0
3948  NaN    128.0
3950  NaN    256.0
3951  NaN    128.0
3955  NaN    256.0
3956  NaN    256.0
3957  NaN    512.0
3959  NaN    256.0
3960  NaN    256.0
3963  NaN    256.0
3973  NaN    128.0
3975  NaN    512.0
3978  NaN    256.0
4012  NaN    512.0
4013  NaN    128.0
4017  NaN    128.0
4019  NaN    128.0
4619  NaN      NaN
5189  NaN    128.0

In [286]:
df.head(10)

,brand,os,cpu_brand,cpu_name,cpu_cores,5g,ram,storage,battery,screen_size,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,1,8.0,128.0,4700.0,6.70,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,1,12.0,256.0,5000.0,6.80,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,1,12.0,256.0,3900.0,6.70,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,6500.0,6.74,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.74,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,1,6.0,128.0,6000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,exynos,exynos 2400,10.0,1,8.0,256.0,5500.0,6.67,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,1,8.0,128.0,5000.0,6.60,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,5000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,1,8.0,256.0,5000.0,6.70,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0

In [287]:
df['ram'] = df['ram'].fillna(df['ram'].mode()[0])

In [288]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   5
battery                  32
screen_size               3
aspect_ratio_category    19
screen_res               18
refresh_rate              0
ppi                      21
rear_cameras              0
rear_primary              1
front_cameras             0
front_primary            45
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [289]:
df = df.dropna(subset=['storage'])

In [290]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                  30
screen_size               3
aspect_ratio_category    19
screen_res               18
refresh_rate              0
ppi                      21
rear_cameras              0
rear_primary              1
front_cameras             0
front_primary            43
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [291]:
df['battery'].value_counts()

battery
5000.0    1927
4000.0     663
3000.0     404
4500.0     395
6000.0     363
          ...
6380.0       1
9000.0       1
2520.0       1
3570.0       1
2560.0       1
Name: count, Length: 314, dtype: int64

In [292]:
df.shape

(6844, 22)

In [293]:
df.loc[df['battery'].isna() , ['battery','price']]

      battery     price
597       NaN   54999.0
601       NaN   16999.0
2583      NaN   26999.0
2925      NaN  169990.0
2930      NaN  149990.0
2945      NaN   48900.0
2946      NaN   64990.0
2949      NaN  119900.0
2956      NaN  109900.0
2962      NaN   64900.0
2979      NaN   24999.0
2980      NaN   49900.0
2986      NaN   59900.0
2997      NaN   49990.0
3003      NaN  106900.0
3004      NaN  104839.0
3005      NaN  123299.0
3006      NaN   54999.0
3030      NaN  104900.0
3722      NaN   29999.0
3723      NaN   42999.0
3724      NaN   24999.0
4036      NaN   23999.0
4235      NaN   17999.0
4592      NaN   12999.0
4605      NaN   24999.0
4617      NaN   17999.0
4822      NaN   12999.0
4876      NaN   49990.0
5552      NaN    3999.0

In [294]:
df.head(50)

,brand,os,cpu_brand,cpu_name,cpu_cores,5g,ram,storage,battery,screen_size,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,samsung,android,exynos,exynos 2400e,10.0,1,8.0,128.0,4700.0,6.70,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,1,12.0,256.0,5000.0,6.80,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,1,12.0,256.0,3900.0,6.70,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,6500.0,6.74,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.74,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0
5,samsung,android,exynos,exynos 1380,8.0,1,6.0,128.0,6000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,79,4.30,13544.0
6,samsung,android,exynos,exynos 2400,10.0,1,8.0,256.0,5500.0,6.67,...,120,394.57,3,50.0,1,12.0,0.0,75,4.70,62990.0
7,samsung,android,exynos,exynos 1480,8.0,1,8.0,128.0,5000.0,6.60,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.35,25999.0
8,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,5000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.65,20400.0
9,samsung,android,snapdragon,snapdragon 7 gen1,8.0,1,8.0,256.0,5000.0,6.70,...,120,392.81,3,50.0,1,50.0,1024.0,84,4.20,18999.0
10,samsung,android,snapdragon,snapdragon 8 elite,8.0,1,12.0,256.0,5000.0,6.90,...,120,498.01,1,200.0,1,12.0,0.0,93,4.15,129999.0
11,samsung,android,exynos,exynos 2400,10.0,1,8.0,256.0,4000.0,6.20,...,120,415.68,3,50.0,1,12.0,0.0,86,4.25,50399.0
12,samsung,android,snapdragon,snapdragon 6 gen3,8.0,1,8.0,128.0,5000.0,6.70,...,120,384.66,3,50.0,1,12.0,0.0,81,4.70,30999.0
13,samsung,android,exynos,exynos,8.0,1,8.0,128.0,5000.0,6.72,...,120,383.51,3,50.0,1,50.0,1024.0,79,4.50,45990.0
14,samsung,android,exynos,exynos 1580,8.0,1,8.0,128.0,5000.0,6.70,...,120,384.66,3,50.0,1,12.0,0.0,83,4.30,38999.0
15,samsung,android,snapdragon,snapdragon 8elite,8.0,1,12.0,256.0,4000.0,6.20,...,120,415.68,3,50.0,1,12.0,0.0,87,4.35,80999.0
16,samsung,android,mediatek,dimensity 6300,8.0,1,6.0,128.0,5000.0,6.74,...,90,260.32,2,50.0,1,8.0,1536.0,74,4.30,9799.0
17,samsung,android,mediatek,dimensity 6300,8.0,1,8.0,128.0,5000.0,6.70,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.65,13499.0
18,samsung,android,exynos,exynos 1480,8.0,1,8.0,128.0,5000.0,6.74,...,120,382.38,3,50.0,1,12.0,0.0,79,4.35,27999.0
19,samsung,android,exynos,exynos 2400e,10.0,1,8.0,256.0,4700.0,6.70,...,120,384.66,3,50.0,1,10.0,0.0,85,4.35,41480.0
20,samsung,android,exynos,exynos 1480,8.0,1,8.0,128.0,5000.0,6.74,...,120,382.38,3,50.0,1,12.0,0.0,79,4.50,27998.0
21,samsung,android,exynos,exynos 2400,10.0,1,12.0,256.0,4900.0,6.70,...,120,512.88,3,50.0,1,12.0,0.0,87,4.15,57000.0
22,samsung,android,mediatek,dimensity 6300,8.0,1,8.0,128.0,5000.0,6.70,...,90,384.66,3,50.0,1,13.0,1536.0,80,4.55,16999.0
23,samsung,android,snapdragon,snapdragon 7 gen1,8.0,1,8.0,128.0,5000.0,6.70,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.60,16372.0
24,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,5000.0,6.70,...,120,384.66,3,50.0,1,13.0,2048.0,82,4.15,20590.0
25,samsung,android,helio,helio g85,8.0,0,4.0,64.0,5000.0,6.70,...,60,261.87,2,50.0,1,8.0,1024.0,69,4.45,6249.0
26,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.70,...,90,384.66,3,50.0,1,13.0,1536.0,74,4.45,10749.0
27,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5800.0,6.70,...,90,261.87,2,50.0,1,8.0,1024.0,74,4.00,9695.0
28,samsung,android,snapdragon,snapdragon 8elite,8.0,1,12.0,512.0,3900.0,6.70,...,120,512.88,2,200.0,1,12.0,0.0,89,4.10,109999.0
29,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,6000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,81,4.75,15429.0
30,samsung,android,exynos,exynos 1480,8.0,1,8.0,256.0,5000.0,6.60,...,120,390.49,3,50.0,1,32.0,1024.0,85,4.60,27999.0
31,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.70,...,90,384.66,3,50.0,1,13.0,1536.0,75,4.20,10749.0
32,samsung,android,exynos,exynos 2400,10.0,1,8.0,128.0,4000.0,6.20,...,120,415.68,3,50.0,1,12.0,0.0,86,4.65,44170.0
33,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,1,12.0,256.0,5000.0,6.80,...,120,501.07,1,200.0,1,12.0,0.0,91,4.05,89499.0
34,samsung,android,mediatek,dimensity 6300,8.0,1,6.0,128.0,5000.0,6.70,...,90,384.66,3,50.0,1,13.0,1536.0,78,4.10,11999.0
35,samsung,android,snapdragon,snapdragon 8 elite,8.0,1,12.0,256.0,4400.0,8.20,...,120,406.96,3,200.0,2,10.0,0.0,94,4.40,169990.0
36,samsung,android,snapdragon,snapdragon 7 gen1,8.0,1,8.0,128.0,5000.0,6.70,...,120,392.81,3,50.0,1,50.0,1024.0,83,4.05,17799.0
37,samsung,android,snapdragon,snapdragon 8 gen 2,8.0,1,8.0,128.0,3900.0,6.10,...,120,422.49,3,50.0,1,12.0,0.0,85,4.20,44999.0
38,samsung,android,exynos,exynos 1380,8.0,1,8.0,256.0,5000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,83,4.25,23043.0
39,samsung,android,mediatek,dimensity 6100 plus,8.0,1,6.0,128.0,6000.0,6.45,...,90,399.57,3,50.0,1,13.0,1024.0,75,4.15,12165.0
40,samsung,android,snapdragon,snapdragon 8 gen3,8.0,1,12.0,512.0,5000.0,6.80,...,120,505.33,1,200.0,1,12.0,0.0,93,4.30,86999.0
41,samsung,android,exynos,exynos,8.0,1,8.0,256.0,4500.0,6.30,...,120,582.78,3,200.0,1,12.0,0.0,80,4.00,49990.0
42,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,64.0,5000.0,6.74,...,90,260.32,2,50.0,1,8.0,1536.0,70,4.65,7999.0
43,samsung,android,snapdragon,snapdragon 7+ gen2,8.0,1,8.0,128.0,5000.0,6.78,...,120,389.79,1,108.0,1,32.0,1024.0,89,4.75,42990.0
44,samsung,android,snapdragon,snapdragon 7 gen1,8.0,1,12.0,256.0,5000.0,6.70,...,120,392.81,3,50.0,1,50.0,1024.0,85,4.50,23999.0
45,samsung,android,exynos,exynos 2200,8.0,1,8.0,128.0,4500.0,6.40,...,120,402.69,3,50.0,1,10.0,0.0,81,4.55,37850.0
46,samsung,android,exynos,exynos 1480,8.0,1,12.0,256.0,5000.0,6.60,...,120,390.49,3,50.0,1,32.0,1024.0,86,4.15,30999.0
47,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,64.0,5000.0,6.70,...,60,261.87,2,50.0,1,8.0,1024.0,70,4.05,7999.0
48,samsung,android,exynos,exynos 1380,8.0,1,8.0,256.0,6000.0,6.60,...,120,390.49,3,50.0,1,13.0,1024.0,82,4.50,19220.0
49,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.70,...,60,261.87,2,50.0,1,8.0,1024.0,72,4.05,8499.0

In [295]:
df['battery'] = df['battery'].fillna(df['battery'].mode()[0])

In [296]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                   0
screen_size               3
aspect_ratio_category    19
screen_res               18
refresh_rate              0
ppi                      21
rear_cameras              0
rear_primary              1
front_cameras             0
front_primary            43
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [297]:
df = df.dropna(subset=['screen_size'])

In [298]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                   0
screen_size               0
aspect_ratio_category    18
screen_res               17
refresh_rate              0
ppi                      18
rear_cameras              0
rear_primary              1
front_cameras             0
front_primary            43
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [299]:
df = df.dropna(subset=['rear_primary'])

In [300]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                   0
screen_size               0
aspect_ratio_category    18
screen_res               17
refresh_rate              0
ppi                      18
rear_cameras              0
rear_primary              0
front_cameras             0
front_primary            42
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [301]:
df['aspect_ratio_category'].value_counts()

aspect_ratio_category
Ultra Tall (20+:9)            3614
Modern Tall (18:9 to 20:9)    1710
Classic Widescreen (16:9)     1407
Standard (16:10 or 4:3)         87
UltraWide / Foldable             4
Name: count, dtype: int64

In [302]:
df.loc[df['aspect_ratio_category'].isna() , ['price' , 'aspect_ratio_category']]

        price aspect_ratio_category
1843   8499.0                   NaN
3722  29999.0                   NaN
3723  42999.0                   NaN
3921   3999.0                   NaN
3924   4299.0                   NaN
3925   3999.0                   NaN
4129   5499.0                   NaN
4637   6199.0                   NaN
4976  10999.0                   NaN
4980   8999.0                   NaN
5059  28000.0                   NaN
5334   8999.0                   NaN
5535   6499.0                   NaN
5543   3900.0                   NaN
5644  21999.0                   NaN
6406   9999.0                   NaN
6662   4100.0                   NaN
6707   4499.0                   NaN

In [303]:
df.loc[
    df['aspect_ratio_category'] == 'Ultra Tall (20+:9)',
    [ 'screen_size', 'aspect_ratio_category', 'price']
]

      screen_size aspect_ratio_category    price
4            6.74    Ultra Tall (20+:9)   7999.0
6            6.67    Ultra Tall (20+:9)  62990.0
9            6.70    Ultra Tall (20+:9)  18999.0
16           6.74    Ultra Tall (20+:9)   9799.0
23           6.70    Ultra Tall (20+:9)  16372.0
...           ...                   ...      ...
6788         6.70    Ultra Tall (20+:9)  51990.0
6789         6.20    Ultra Tall (20+:9)  41990.0
6790         6.70    Ultra Tall (20+:9)  55999.0
6791         6.20    Ultra Tall (20+:9)  49499.0
6794         6.50    Ultra Tall (20+:9)  13999.0

[3614 rows x 3 columns]

In [304]:
df['aspect_ratio_category'] = df['aspect_ratio_category'].fillna(df['aspect_ratio_category'].mode()[0])

In [305]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                   0
screen_size               0
aspect_ratio_category     0
screen_res               17
refresh_rate              0
ppi                      18
rear_cameras              0
rear_primary              0
front_cameras             0
front_primary            42
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [306]:
df['screen_res'].value_counts()

screen_res
FHD+         2919
HD+          1575
HD            644
QHD+          641
FHD           507
qHD           256
QHD           179
4K UHD         86
Ultra HD+      16
Name: count, dtype: int64

In [307]:
df['screen_res'] = df['screen_res'].fillna(df['screen_res'].mode()[0])

In [308]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                   0
screen_size               0
aspect_ratio_category     0
screen_res                0
refresh_rate              0
ppi                      18
rear_cameras              0
rear_primary              0
front_cameras             0
front_primary            42
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [309]:
df['ppi'].value_counts()

ppi
293.72    368
394.57    316
269.93    228
400.53    224
267.02    155
         ...
293.29      1
447.37      1
291.90      1
402.25      1
545.44      1
Name: count, Length: 709, dtype: int64

In [310]:
df = df.dropna(subset=['ppi'])

In [311]:
df.isnull().sum()

brand                     0
os                        0
cpu_brand                 0
cpu_name                  0
cpu_cores                 0
5g                        0
ram                       0
storage                   0
battery                   0
screen_size               0
aspect_ratio_category     0
screen_res                0
refresh_rate              0
ppi                       0
rear_cameras              0
rear_primary              0
front_cameras             0
front_primary            40
expandable_upto           0
spec_score                0
user_rating               0
price                     0
dtype: int64

In [312]:
df.loc[df['front_primary'].isna() , ['front_primary' , 'rear_primary']]

      front_primary  rear_primary
376             NaN          48.0
539             NaN          48.0
1699            NaN          13.0
2176            NaN         108.0
2182            NaN          50.0
2187            NaN          13.0
3065            NaN          13.0
3634            NaN          25.0
3967            NaN          40.0
4008            NaN          48.0
4287            NaN         108.0
4288            NaN         108.0
4291            NaN          50.0
4306            NaN          48.0
4308            NaN          24.0
4310            NaN          24.0
4355            NaN           8.0
4489            NaN          64.0
4492            NaN          64.0
4516            NaN          64.0
4518            NaN          64.0
4526            NaN          64.0
4529            NaN          48.0
4530            NaN          48.0
4531            NaN          48.0
4533            NaN          48.0
4542            NaN          48.0
4831            NaN          13.0
4834            NaN          13.0
5027            NaN           8.0
5235            NaN          24.0
5247            NaN          20.0
5252            NaN           5.0
5600            NaN          50.0
5999            NaN          13.0
6116            NaN          12.0
6385            NaN           2.0
6471            NaN           8.0
6655            NaN           5.0
6738            NaN           5.0

In [313]:
df['front_primary'] = df['front_primary'].fillna(df['front_primary'].mode()[0])

In [314]:
df.isnull().sum()

brand                    0
os                       0
cpu_brand                0
cpu_name                 0
cpu_cores                0
5g                       0
ram                      0
storage                  0
battery                  0
screen_size              0
aspect_ratio_category    0
screen_res               0
refresh_rate             0
ppi                      0
rear_cameras             0
rear_primary             0
front_cameras            0
front_primary            0
expandable_upto          0
spec_score               0
user_rating              0
price                    0
dtype: int64

In [315]:
df.shape

(6822, 22)

In [316]:
df['memory_score'] = df['ram'] + df['storage']

In [317]:
df['back_camera_score'] = df['rear_cameras'] + df['rear_primary']

In [318]:
df.head()

,brand,os,cpu_brand,cpu_name,cpu_cores,5g,ram,storage,battery,screen_size,...,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price,memory_score,back_camera_score
0,samsung,android,exynos,exynos 2400e,10.0,1,8.0,128.0,4700.0,6.70,...,3,50.0,1,10.0,0.0,84,4.00,34999.0,136.0,53.0
1,samsung,android,snapdragon,snapdragon 8 gen3,8.0,1,12.0,256.0,5000.0,6.80,...,1,200.0,1,12.0,0.0,92,4.35,84949.0,268.0,201.0
2,samsung,android,snapdragon,snapdragon 8elite,8.0,1,12.0,256.0,3900.0,6.70,...,2,200.0,1,12.0,0.0,89,4.45,109999.0,268.0,202.0
3,samsung,android,exynos,exynos 1380,8.0,1,8.0,128.0,6500.0,6.74,...,3,50.0,1,16.0,1024.0,82,4.55,19990.0,136.0,53.0
4,samsung,android,mediatek,dimensity 6300,8.0,1,4.0,128.0,5000.0,6.74,...,2,50.0,1,8.0,1536.0,72,4.00,7999.0,132.0,52.0

In [319]:
df.shape

(6822, 24)

Lets Encode the categorical features

In [320]:
df.brand.value_counts()

brand
samsung       627
vivo          604
xiaomi        580
realme        495
oppo          406
huawei        330
motorola      323
tecno         210
honor         196
infinix       174
oneplus       171
iqoo          168
nokia         161
lg            152
zte           147
asus          141
lenovo        139
lava          138
poco          132
apple         121
ikall         119
micromax       98
sony           96
nubia          95
intex          92
meizu          91
htc            89
itel           87
ulefone        80
doogee         78
gionee         69
panasonic      68
tcl            65
google         58
alcatel        57
karbonn        46
hmd            26
spice          26
nothing        22
acer           19
blackberry      9
cmf             5
redmi           4
jio             4
acerone         2
jmax            2
Name: count, dtype: int64

In [321]:
from sklearn.preprocessing  import LabelEncoder

le = LabelEncoder()

df['brand'] = le.fit_transform(df['brand'])

In [322]:
df['brand'].value_counts()

brand
37    627
43    604
44    580
35    495
32    406
13    330
27    323
41    210
11    196
15    174
31    171
17    168
28    161
24    152
45    147
4     141
23    139
22    138
34    132
3     121
14    119
26     98
38     96
30     95
16     92
25     91
12     89
18     87
42     80
7      78
8      69
33     68
40     65
9      58
2      57
21     46
10     26
39     26
29     22
0      19
5       9
6       5
36      4
19      4
1       2
20      2
Name: count, dtype: int64

In [323]:
df['os'].value_counts()

os
android    6630
ios         121
other        61
windows      10
Name: count, dtype: int64

In [324]:
df['os'] = le.fit_transform(df['os'])

In [325]:
df['os'].value_counts()

os
0    6630
1     121
2      61
3      10
Name: count, dtype: int64

In [326]:
df['cpu_brand'].value_counts()

cpu_brand
snapdragon    2764
mediatek      1590
helio         1361
exynos         270
unisoc         231
kirin          219
other          198
apple           95
qualcomm        57
google          21
intel           11
samsung          5
Name: count, dtype: int64

In [327]:
df['cpu_brand'] = le.fit_transform(df['cpu_brand'])

In [328]:
df.cpu_brand.value_counts()

cpu_brand
10    2764
6     1590
3     1361
1      270
11     231
5      219
7      198
0       95
8       57
2       21
4       11
9        5
Name: count, dtype: int64

In [329]:
df.cpu_name.value_counts()

cpu_name
helio mt6732 / spreadtrum sc9832e    466
dimensity 6300                       125
snapdragon 8 gen2                     82
helio p22                             80
dimensity 700 5g                      80
                                    ...
helio  mt6762d                         1
helio mt6580m                          1
mediatek mt6739                        1
9832e                                  1
unisoc 9832e                           1
Name: count, Length: 824, dtype: int64

In [330]:
df.ram.value_counts()

ram
8.0     1740
4.0     1424
6.0     1111
2.0      739
3.0      693
12.0     614
1.0      359
16.0      91
1.5       28
24.0      10
18.0       7
10.0       6
Name: count, dtype: int64

In [331]:
df['ram'] = le.fit_transform(df['ram'])

df['ram'].value_counts()

ram
6     1740
4     1424
5     1111
2      739
3      693
8      614
0      359
9       91
1       28
11      10
10       7
7        6
Name: count, dtype: int64

In [332]:
df['storage'].value_counts()

storage
128.00     2349
64.00      1245
256.00     1180
32.00       806
16.00       677
8.00        250
512.00      221
4.00         50
1024.00      33
258.00        2
1.70          2
5.00          2
15.00         1
1.17          1
12.47         1
2.00          1
1.40          1
Name: count, dtype: int64

In [333]:
df['storage'] = le.fit_transform(df['storage'])

df['storage'].value_counts()

storage
12    2349
11    1245
13    1180
10     806
9      677
6      250
15     221
4       50
16      33
14       2
2        2
5        2
8        1
0        1
7        1
3        1
1        1
Name: count, dtype: int64

In [334]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6822 entries, 0 to 6855
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  6822 non-null   int64
 1   os                     6822 non-null   int64
 2   cpu_brand              6822 non-null   int64
 3   cpu_name               6822 non-null   object
 4   cpu_cores              6822 non-null   float64
 5   5g                     6822 non-null   int64
 6   ram                    6822 non-null   int64
 7   storage                6822 non-null   int64
 8   battery                6822 non-null   float64
 9   screen_size            6822 non-null   float64
 10  aspect_ratio_category  6822 non-null   object
 11  screen_res             6822 non-null   object
 12  refresh_rate           6822 non-null   int64
 13  ppi                    6822 non-null   float64
 14  rear_cameras           6822 non-null   int64
 15  rear_primary           6822 non-null   float64
 16  front_cameras          6822 non-null   int64
 17  front_primary          6822 non-null   float64
 18  expandable_upto        6822 non-null   float64
 19  spec_score             6822 non-null   int64
 20  user_rating            6822 non-null   float64
 21  price                  6822 non-null   float64
 22  memory_score           6822 non-null   float64
 23  back_camera_score      6822 non-null   float64
dtypes: float64(11), int64(10), object(3)
memory usage: 1.3+ MB

In [335]:
df['aspect_ratio_category'].value_counts()

aspect_ratio_category
Ultra Tall (20+:9)            3614
Modern Tall (18:9 to 20:9)    1710
Classic Widescreen (16:9)     1407
Standard (16:10 or 4:3)         87
UltraWide / Foldable             4
Name: count, dtype: int64

In [336]:
df['aspect_ratio_category'] = le.fit_transform(df['aspect_ratio_category'])

df['aspect_ratio_category'].value_counts()

aspect_ratio_category
3    3614
1    1710
0    1407
2      87
4       4
Name: count, dtype: int64

In [337]:
df['screen_res'].value_counts()

screen_res
FHD+         2918
HD+          1575
HD            644
QHD+          641
FHD           507
qHD           256
QHD           179
4K UHD         86
Ultra HD+      16
Name: count, dtype: int64

In [338]:
df['screen_res'] = le.fit_transform(df['screen_res'])

df['screen_res'].value_counts()

screen_res
2    2918
4    1575
3     644
6     641
1     507
8     256
5     179
0      86
7      16
Name: count, dtype: int64

In [339]:
df.cpu_cores.value_counts()

cpu_cores
8.0     5479
4.0     1168
6.0      123
2.0       35
10.0      17
Name: count, dtype: int64

In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6822 entries, 0 to 6855
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  6822 non-null   int64
 1   os                     6822 non-null   int64
 2   cpu_brand              6822 non-null   int64
 3   cpu_name               6822 non-null   object
 4   cpu_cores              6822 non-null   float64
 5   5g                     6822 non-null   int64
 6   ram                    6822 non-null   int64
 7   storage                6822 non-null   int64
 8   battery                6822 non-null   float64
 9   screen_size            6822 non-null   float64
 10  aspect_ratio_category  6822 non-null   int64
 11  screen_res             6822 non-null   int64
 12  refresh_rate           6822 non-null   int64
 13  ppi                    6822 non-null   float64
 14  rear_cameras           6822 non-null   int64
 15  rear_primary           6822 non-null   float64
 16  front_cameras          6822 non-null   int64
 17  front_primary          6822 non-null   float64
 18  expandable_upto        6822 non-null   float64
 19  spec_score             6822 non-null   int64
 20  user_rating            6822 non-null   float64
 21  price                  6822 non-null   float64
 22  memory_score           6822 non-null   float64
 23  back_camera_score      6822 non-null   float64
dtypes: float64(11), int64(12), object(1)
memory usage: 1.3+ MB

In [341]:
df.drop(columns=['cpu_name'] , inplace=True)

In [342]:
df.head()

,brand,os,cpu_brand,cpu_cores,5g,ram,storage,battery,screen_size,aspect_ratio_category,...,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price,memory_score,back_camera_score
0,37,0,1,10.0,1,6,12,4700.0,6.70,1,...,3,50.0,1,10.0,0.0,84,4.00,34999.0,136.0,53.0
1,37,0,10,8.0,1,8,13,5000.0,6.80,1,...,1,200.0,1,12.0,0.0,92,4.35,84949.0,268.0,201.0
2,37,0,10,8.0,1,8,13,3900.0,6.70,1,...,2,200.0,1,12.0,0.0,89,4.45,109999.0,268.0,202.0
3,37,0,1,8.0,1,6,12,6500.0,6.74,1,...,3,50.0,1,16.0,1024.0,82,4.55,19990.0,136.0,53.0
4,37,0,6,8.0,1,4,12,5000.0,6.74,3,...,2,50.0,1,8.0,1536.0,72,4.00,7999.0,132.0,52.0

In [343]:
df.drop(columns=['memory_score' , 'back_camera_score'] , inplace=True)

In [344]:
df.head()

,brand,os,cpu_brand,cpu_cores,5g,ram,storage,battery,screen_size,aspect_ratio_category,...,refresh_rate,ppi,rear_cameras,rear_primary,front_cameras,front_primary,expandable_upto,spec_score,user_rating,price
0,37,0,1,10.0,1,6,12,4700.0,6.70,1,...,120,384.66,3,50.0,1,10.0,0.0,84,4.00,34999.0
1,37,0,10,8.0,1,8,13,5000.0,6.80,1,...,120,505.33,1,200.0,1,12.0,0.0,92,4.35,84949.0
2,37,0,10,8.0,1,8,13,3900.0,6.70,1,...,120,512.88,2,200.0,1,12.0,0.0,89,4.45,109999.0
3,37,0,1,8.0,1,6,12,6500.0,6.74,1,...,120,382.38,3,50.0,1,16.0,1024.0,82,4.55,19990.0
4,37,0,6,8.0,1,4,12,5000.0,6.74,3,...,90,260.32,2,50.0,1,8.0,1536.0,72,4.00,7999.0

In [345]:
num_df = df.select_dtypes(include=['int64', 'float64'])
corr_matrix = num_df.corr()
corr_with_price = corr_matrix['price'].sort_values(ascending=False)
print(corr_with_price)

price                    1.000000
spec_score               0.564996
ram                      0.546987
storage                  0.521375
ppi                      0.500912
5g                       0.431808
refresh_rate             0.381261
screen_size              0.372049
front_primary            0.333789
rear_primary             0.332248
rear_cameras             0.300933
os                       0.231005
cpu_cores                0.214946
front_cameras            0.172833
battery                  0.150444
cpu_brand                0.134758
aspect_ratio_category    0.122969
user_rating              0.085834
screen_res               0.024620
brand                   -0.074727
expandable_upto         -0.165555
Name: price, dtype: float64

Lets Drop Weak Features

In [346]:
df.drop(
    columns=[
        'screen_res',
        'brand',
        'expandable_upto',
        'user_rating',
        'aspect_ratio_category'
    ],
    inplace=True
)

In [347]:
df.shape

(6822, 16)

Lets  Split the data and train the data Implement Artificial Neural Network

In [348]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout , BatchNormalization
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error  , r2_score

In [349]:
X = df.drop(columns=['price'])
y = df['price']

In [350]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [351]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [352]:
X_train_scaled.shape

(5457, 15)

In [353]:
X_train_scaled

array([[-0.15545309,  0.97779568,  0.4755604 , ..., -0.16693612,
        -0.59155327,  0.26961795],
       [-0.15545309, -0.60854961,  0.4755604 , ..., -0.16693612,
         0.10949114, -0.80972979],
       [-0.15545309,  0.97779568, -2.09387832, ..., -0.16693612,
        -0.85444492, -1.73488501],
       ...,
       [-0.15545309, -1.24308773,  0.4755604 , ..., -0.16693612,
        -0.85444492, -1.73488501],
       [-0.15545309, -1.24308773,  0.4755604 , ..., -0.16693612,
        -0.85444492, -0.50134472],
       [-0.15545309, -1.24308773,  0.4755604 , ..., -0.16693612,
        -0.59155327, -0.03876712]])

In [354]:
import xgboost as xgb
from xgboost import XGBRegressor

In [355]:
model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.01,
    max_depth=3,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    min_samples_split=2,
    min_samples_leaf=1,
    reg_alpha=0.1,
    reg_lambda=1
)

In [356]:
model.fit(X_train_scaled , y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:49:02] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, min_samples_leaf=1,
             min_samples_split=2, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=500, ...)

In [357]:
y_pred = model.predict(X_test_scaled)

In [358]:
score = r2_score(y_test , y_pred)

In [359]:
score

0.773698368469449

In [360]:
score2 = r2_score(y_train , model.predict(X_train_scaled))

In [361]:
score2

0.7889679196347387

In [362]:
# Import GridSearchCV

from sklearn.model_selection import RandomizedSearchCV

In [364]:
CV = RandomizedSearchCV(
    estimator=model,
    param_distributions={
        'n_estimators': [50, 100, 200, 300, 400, 500],
        'learning_rate': [0.01, 0.1, 0.2, 0.3],
        'max_depth': [3, 4, 5, 6, 7],
        'subsample': [0.8, 0.9, 1.0],
        'colsample_bytree': [0.8, 0.9, 1.0],
        'random_state': [42],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'reg_alpha': [0.1, 0.5, 1],
        'reg_lambda': [0.1, 0.5, 1]
    },
    scoring='neg_mean_squared_error',
    cv=5,
)

In [365]:
CV.fit(X_train_scaled , y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:23] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:28] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:29] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:29] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:31] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [11:50:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=0.8, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints...
                                          multi_strategy=None, n_estimators=500, ...),
                   param_distributions={'colsample_bytree': [0.8, 0.9, 1.0],
                                        'learning_rate': [0.01, 0.1, 0.2, 0.3],
                                        'max_depth': [3, 4, 5, 6, 7],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 200, 300, 400,
                                                         500],
                                        'random_state': [42],
                                        'reg_alpha': [0.1, 0.5, 1],
                                        'reg_lambda': [0.1, 0.5, 1],
                                        'subsample': [0.8, 0.9, 1.0]},
                   scoring='neg_mean_squared_error')

In [366]:
y_pred2 = CV.predict(X_test_scaled)

In [367]:
score2 = r2_score(y_test , y_pred2)

In [368]:
score3 = r2_score(y_train , CV.predict(X_train_scaled))

In [369]:
score2

0.7749862022600861

In [370]:
score3

0.8974553945067939