<a href="https://colab.research.google.com/github/Bryan-eng-lng/Machine-Learning-Projects-/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lets look at data and analyse data

In [1]:
import pandas as pd


df = pd.read_csv("/content/The Titanic dataset.csv")

In [2]:
print(df.shape)

(1302, 10)

In [3]:
print(df.head())

    1       2         3                            4       5    6       7  \
0  sn  pclass  survived                          NaN  gender  age  family
1   1       3         0                  Mr. Anthony    male   42       0
2   1       3         0                  Mr. Anthony    male   42       0
3   2       3         0        Master. Eugene Joseph    male    ?       2
4   3       2         0  Abbott, Mr. Rossmore Edward     NaN  NaN       2

       8         9         10
0   fare  embarked       date
1   7.55       NaN  01-Jan-90
2   7.55       NaN  01-Jan-90
3  20.25         S  02-Jan-90
4     **         S  03-Jan-90

In [4]:
df.head()

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90

In [5]:
print(df.columns)

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='object')

In [6]:
print(df.isnull().sum())

1       0
2       0
3       0
4       1
5       1
6     257
7       2
8       2
9       6
10      0
dtype: int64

In [8]:
df['3'].value_counts()

3
0           801
1           500
survived      1
Name: count, dtype: int64

survived = 1 and not survived = 0

In [9]:
df['1'].value_counts()

1
1      2
873    1
872    1
871    1
870    1
      ..
429    1
428    1
427    1
426    1
436    1
Name: count, Length: 1301, dtype: int64

In [11]:
df = df.drop(columns=['1'] , axis=1)

print(df.head())

        2         3                            4       5    6       7      8  \
0  pclass  survived                          NaN  gender  age  family   fare
1       3         0                  Mr. Anthony    male   42       0   7.55
2       3         0                  Mr. Anthony    male   42       0   7.55
3       3         0        Master. Eugene Joseph    male    ?       2  20.25
4       2         0  Abbott, Mr. Rossmore Edward     NaN  NaN       2     **

          9         10
0  embarked       date
1       NaN  01-Jan-90
2       NaN  01-Jan-90
3         S  02-Jan-90
4         S  03-Jan-90

In [12]:
df.head()

,2,3,4,5,6,7,8,9,10
0,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90

2 - pclass  , 3 - survived , 4 - NaN , 5 - gender , 6 - age , 7 - family , 8 - fare , 9 - embarked , 10 - date

In [16]:
df['2'].value_counts()

2
3         700
1         323
2         278
pclass      1
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1302 entries, 0 to 1301
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2       1302 non-null   object
 1   3       1302 non-null   object
 2   4       1301 non-null   object
 3   5       1301 non-null   object
 4   6       1045 non-null   object
 5   7       1300 non-null   object
 6   8       1300 non-null   object
 7   9       1296 non-null   object
 8   10      1302 non-null   object
dtypes: object(9)
memory usage: 91.7+ KB

In [20]:
df = df.drop(index=0)
print(df.head())

   2  3                            4       5    6  7      8    9         10
1  3  0                  Mr. Anthony    male   42  0   7.55  NaN  01-Jan-90
2  3  0                  Mr. Anthony    male   42  0   7.55  NaN  01-Jan-90
3  3  0        Master. Eugene Joseph    male    ?  2  20.25    S  02-Jan-90
4  2  0  Abbott, Mr. Rossmore Edward     NaN  NaN  2     **    S  03-Jan-90
5  3  1  Abbott, Mr. Rossmore Edward  female   35  2  20.25    S  04-Jan-90

In [21]:
df.rename(columns={'2': 'pclass', '3': 'survived', '4': 'name', '5': 'gender', '6': 'age', '7': 'family', '8': 'fare', '9': 'embarked', '10': 'date'}, inplace=True)
print(df.head())

  pclass survived                         name  gender  age family   fare  \
1      3        0                  Mr. Anthony    male   42      0   7.55
2      3        0                  Mr. Anthony    male   42      0   7.55
3      3        0        Master. Eugene Joseph    male    ?      2  20.25
4      2        0  Abbott, Mr. Rossmore Edward     NaN  NaN      2     **
5      3        1  Abbott, Mr. Rossmore Edward  female   35      2  20.25

  embarked       date
1      NaN  01-Jan-90
2      NaN  01-Jan-90
3        S  02-Jan-90
4        S  03-Jan-90
5        S  04-Jan-90

In [24]:
df = df.drop(columns=['name'], index=1)

print(df.head())

  pclass survived  gender  age family   fare embarked       date
2      3        0    male   42      0   7.55      NaN  01-Jan-90
3      3        0    male    ?      2  20.25        S  02-Jan-90
4      2        0     NaN  NaN      2     **        S  03-Jan-90
5      3        1  female   35      2  20.25        S  04-Jan-90
6      3        1  female   16      0   7.65        S  05-Jan-90

In [26]:
df.isnull().sum()

pclass        0
survived      0
gender        1
age         257
family        2
fare          2
embarked      5
date          0
dtype: int64

In [30]:
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [32]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])

In [35]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].fillna(df['age'].mean())

In [37]:
df['fare'].value_counts()

fare
13        59
8.05      58
7.75      55
26        50
7.8958    49
          ..
9.325      1
7.7792     1
**         1
35         1
7.875      1
Name: count, Length: 282, dtype: int64

In [39]:
df['fare'] = pd.to_numeric(df['fare'], errors='coerce')
df['fare'] = df['fare'].fillna(df['fare'].mean())

In [41]:
df['embarked'].value_counts()

embarked
S    905
C    267
Q    123
Name: count, dtype: int64

In [42]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

In [43]:
df['embarked'] = le.fit_transform(df['embarked'])

print(df.head())

  pclass survived  gender        age family      fare  embarked       date
2      3        0       1  42.000000      0   7.55000         2  01-Jan-90
3      3        0       1  29.967294      2  20.25000         2  02-Jan-90
4      2        0       1  29.967294      2  33.48216         2  03-Jan-90
5      3        1       0  35.000000      2  20.25000         2  04-Jan-90
6      3        1       0  16.000000      0   7.65000         2  05-Jan-90

In [46]:
df = df.drop(columns=['date'] , axis=1)

In [48]:
corr = df.corr()

corr

            pclass  survived    gender       age    family      fare  embarked
pclass    1.000000 -0.308653  0.121571 -0.364157  0.051201 -0.557384  0.187452
survived -0.308653  1.000000 -0.528300 -0.051457  0.025424  0.242477 -0.177608
gender    0.121571 -0.528300  1.000000  0.062005 -0.188046 -0.184374  0.096733
age      -0.364157 -0.051457  0.062005  1.000000 -0.194858  0.169801 -0.073235
family    0.051201  0.025424 -0.188046 -0.194858  1.000000  0.226604  0.068687
fare     -0.557384  0.242477 -0.184374  0.169801  0.226604  1.000000 -0.239389
embarked  0.187452 -0.177608  0.096733 -0.073235  0.068687 -0.239389  1.000000

In [49]:
df = df.drop(columns=['family'] , axis=1)

In [50]:
df.head()

  pclass survived  gender        age      fare  embarked
2      3        0       1  42.000000   7.55000         2
3      3        0       1  29.967294  20.25000         2
4      2        0       1  29.967294  33.48216         2
5      3        1       0  35.000000  20.25000         2
6      3        1       0  16.000000   7.65000         2