<a href="https://colab.research.google.com/github/Bryan-eng-lng/Machine-Learning-Projects-/blob/main/XGBClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Dependencies

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import xgboost as xgb

In [3]:
df = pd.read_csv("/content/Student_Performance (1).csv")

In [4]:
df.head()

   student_id  age  gender  ... english_score overall_score  final_grade
0           1   14    male  ...          57.0          53.1            e
1           2   18  female  ...          64.8          61.3            d
2           3   17  female  ...          79.2          89.6            b
3           4   16   other  ...          54.7          41.6            e
4           5   16  female  ...          30.0          25.4            f

[5 rows x 16 columns]

In [5]:
df.final_grade.value_counts()

final_grade
d    6311
c    6161
e    5672
f    2955
b    2696
a    1205
Name: count, dtype: int64

In [6]:
df.shape

(25000, 16)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             25000 non-null  int64
 1   age                    25000 non-null  int64
 2   gender                 25000 non-null  object
 3   school_type            25000 non-null  object
 4   parent_education       25000 non-null  object
 5   study_hours            25000 non-null  float64
 6   attendance_percentage  25000 non-null  float64
 7   internet_access        25000 non-null  object
 8   travel_time            25000 non-null  object
 9   extra_activities       25000 non-null  object
 10  study_method           25000 non-null  object
 11  math_score             25000 non-null  float64
 12  science_score          25000 non-null  float64
 13  english_score          25000 non-null  float64
 14  overall_score          25000 non-null  float64
 15  final_grade            25000 non-null  object
dtypes: float64(6), int64(2), object(8)
memory usage: 3.1+ MB

In [8]:
df.describe()

        student_id           age  ...  english_score  overall_score
count  25000.00000  25000.000000  ...   25000.000000   25000.000000
mean    7493.04380     16.482760  ...      63.681948      64.006172
std     4323.56215      1.703895  ...      20.792693      18.932025
min        1.00000     14.000000  ...       0.000000      14.500000
25%     3743.75000     15.000000  ...      48.300000      49.000000
50%     7461.50000     16.000000  ...      64.200000      64.200000
75%    11252.00000     18.000000  ...      80.000000      79.000000
max    15000.00000     19.000000  ...     100.000000     100.000000

[8 rows x 8 columns]

In [9]:
df = df.drop(columns=['student_id','gender'])

In [10]:
df.head()

   age school_type parent_education  ...  english_score  overall_score final_grade
0   14      public    post graduate  ...           57.0           53.1           e
1   18      public         graduate  ...           64.8           61.3           d
2   17     private    post graduate  ...           79.2           89.6           b
3   16      public      high school  ...           54.7           41.6           e
4   16      public      high school  ...           30.0           25.4           f

[5 rows x 14 columns]

In [11]:
df.study_method.value_counts()

study_method
mixed            4341
textbook         4239
notes            4165
online videos    4139
group study      4090
coaching         4026
Name: count, dtype: int64

In [12]:
df.travel_time.value_counts()

travel_time
15-30 min    6362
30-60 min    6345
>60 min      6166
<15 min      6127
Name: count, dtype: int64

In [16]:
df.dtypes

age                        int64
school_type               object
parent_education          object
study_hours              float64
attendance_percentage    float64
internet_access           object
travel_time               object
extra_activities          object
study_method              object
math_score               float64
science_score            float64
english_score            float64
overall_score            float64
final_grade               object
dtype: object

In [18]:
le = LabelEncoder()

for i in df.columns:
  if df[i].dtype == 'object':
    df[i] = le.fit_transform(df[i])

In [19]:
df.head()

   age  school_type  ...  overall_score  final_grade
0   14            1  ...           53.1            4
1   18            1  ...           61.3            3
2   17            0  ...           89.6            1
3   16            1  ...           41.6            4
4   16            1  ...           25.4            5

[5 rows x 14 columns]

In [20]:
df.tail()

       age  school_type  ...  overall_score  final_grade
24995   17            1  ...           46.1            4
24996   16            0  ...           56.5            3
24997   19            0  ...           36.7            5
24998   14            0  ...           34.1            5
24999   18            1  ...           31.4            5

[5 rows x 14 columns]

Lets Split Data and  Train the Data

In [21]:
X = df.drop(columns=["final_grade"])

y = df["final_grade"]

In [22]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=2)

In [ ]:
model = xgb.XGBClassifier()

model.fit(X_train , y_train)

In [24]:
y_pred = model.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test , y_pred)

In [27]:
accuracy

0.9966